export const movies = [
  {
    poster: "/images/Movies/Posters/01_The Shawshank Redemption.jpg",
    id: "1",
    title: "The Shawshank Redemption",
    rating: 9.3, // Actual IMDb rating
    year: 1994, // Corrected year
    category: "Drama", // Corrected category
    related: "The Shawshank Redemption",
    related_id: "1",
    director: "Frank Darabont", // Corrected director
    actors: [
      { id: 1, actor: "Tim Robbins" },
      { id: 2, actor: "Morgan Freeman" },
      { id: 3, actor: "Bob Gunton" },
      { id: 4, actor: "William Sadler" },
      { id: 5, actor: "Clancy Brown" },
    ],
  },
  {
    poster: "/images/Movies/Posters/02.01_The Godfather.jpg",
    id: "2.01",
    title: "The Godfather",
    rating: 9.2, // Actual IMDb rating
    year: 1972, // Corrected year
    category: "Mafia", // Corrected category
    related: "The Godfather",
    related_id: "1",
    director: "Francis Ford Coppola", // Corrected director
    actors: [
      { id: 1, actor: "Marlon Brando" },
      { id: 2, actor: "Al Pacino" },
      { id: 3, actor: "James Caan" },
      { id: 4, actor: "Richard S. Castellano" },
      { id: 5, actor: "Sterling Hayden" },
    ],
  },
  {
    poster: "/images/Movies/Posters/02.02_The Gadfather Part II.jpg",
    id: "2.02",
    title: "The Godfather Part II",
    rating: 9, // Actual IMDb rating
    year: 1974, // Corrected year
    category: "Mafia", // Corrected category
    related: "The Godfather",
    related_id: "2",
    director: "Francis Ford Coppola", // Corrected director
    actors: [
      { id: 1, actor: "Al Pacino" },
      { id: 2, actor: "Robert De Niro" },
      { id: 3, actor: "Diane Keaton" },
      { id: 4, actor: "John Marley" },
      { id: 5, actor: "Richard S. Castellano" },
    ],
  },
  {
    poster: "/images/Movies/Posters/02.03_The Godfather Part III.jpg",
    id: "2.03",
    title: "The Godfather Part III",
    rating: 7.6, // Actual IMDb rating
    year: 1990, // Corrected year
    category: "Mafia", // Corrected category
    related: "The Godfather",
    related_id: "3",
    director: "Francis Ford Coppola", // Corrected director
    actors: [
      { id: 1, actor: "Al Pacino" },
      { id: 2, actor: "Diane Keaton" },
      { id: 3, actor: "Andy Garcia" },
      { id: 4, actor: "Talia Shire" },
      { id: 5, actor: "Joe Mantegna" },
    ],
  },
  {
    poster: "/images/Movies/Posters/03.01_Batman Begins.jpg",
    id: "3.01",
    title: "Batman Begins",
    rating: 8.3, // Actual IMDb rating
    year: 2005, // Corrected year
    category: "Action-Crime", // Corrected category
    related: "Batman Nolan",
    related_id: "1",
    director: "Christopher Nolan", // Corrected director
    actors: [
      { id: 1, actor: "Christian Bale" },
      { id: 2, actor: "Michael Caine" },
      { id: 3, actor: "Liam Neeson" },
      { id: 4, actor: "Katie Holmes" },
      { id: 5, actor: "Gary Oldman" },
    ],
  },
  {
    poster: "/images/Movies/Posters/03.02_The Dark Knight.jpg",
    id: "3.02",
    title: "The Dark Knight",
    rating: 9, // Actual IMDb rating
    year: 2008, // Corrected year
    category: "Action-Crime", // Corrected category
    related: "Batman Nolan",
    related_id: "2",
    director: "Christopher Nolan", // Corrected director
    actors: [
      { id: 1, actor: "Christian Bale" },
      { id: 2, actor: "Heath Ledger" },
      { id: 3, actor: "Aaron Eckhart" },
      { id: 4, actor: "Maggie Gyllenhaal" },
      { id: 5, actor: "Gary Oldman" },
    ],
  },
  {
    poster: "/images/Movies/Posters/03.03_The Dark Knight rises.jpg",
    id: "3.03",
    title: "The Dark Knight Rises",
    rating: 8.4, // Actual IMDb rating
    year: 2012, // Corrected year
    category: "Action-Crime", // Corrected category
    related: "Batman Nolan",
    related_id: "3",
    director: "Christopher Nolan", // Corrected director
    actors: [
      { id: 1, actor: "Christian Bale" },
      { id: 2, actor: "Tom Hardy" },
      { id: 3, actor: "Anne Hathaway" },
      { id: 4, actor: "Gary Oldman" },
      { id: 5, actor: "Joseph Gordon-Levitt" },
    ],
  },
  {
    poster: "/images/Movies/Posters/05_12 Angry Men.jpg",
    id: "5",
    title: "12 Angry Men",
    rating: 9, // Actual IMDb rating
    year: 1957, // Corrected year
    category: "Drama", // Corrected category
    related: "12 Angry Men",
    related_id: "1",
    director: "Sidney Lumet", // Corrected director
    actors: [
      { id: 1, actor: "Henry Fonda" },
      { id: 2, actor: "Lee J. Cobb" },
      { id: 3, actor: "Martin Balsam" },
      { id: 4, actor: "John Fiedler" },
      { id: 5, actor: "E.G. Marshall" },
    ],
  },
  {
    poster: "/images/Movies/Posters/06_Schindler's List.jpg",
    id: "6",
    title: "Schindler's List",
    rating: 9, // Actual IMDb rating
    year: 1993, // Corrected year
    category: "War", // Corrected category
    related: "Schindler's List",
    related_id: "1",
    director: "Steven Spielberg", // Corrected director
    actors: [
      { id: 1, actor: "Liam Neeson" },
      { id: 2, actor: "Ben Kingsley" },
      { id: 3, actor: "Ralph Fiennes" },
      { id: 4, actor: "Caroline Goodall" },
      { id: 5, actor: "Jonathan Sagall" },
    ],
  },
  {
    poster:
      "/images/Movies/Posters/07.01_The Hobbit - An Unexpected Journey.jpg",
    id: "7.01",
    title: "The Hobbit - An Unexpected Journey",
    rating: 7.8,
    year: 2012,
    category: "Fantasy",
    related: "lotr",
    related_id: "1",
    director: "Peter Jackson",
    actors: [
      { id: 1, actor: "Martin Freeman" },
      { id: 2, actor: "Ian McKellen" },
      { id: 3, actor: "Richard Armitage" },
      { id: 4, actor: "Ken Stott" },
      { id: 5, actor: "Graham McTavish" },
    ],
  },
  {
    poster:
      "/images/Movies/Posters/07.02_The Hobbit - The Desolation of Smaug.jpg",
    id: "7.02",
    title: "The Hobbit - The Desolation of Smaug",
    rating: 7.8,
    year: 2013,
    category: "Fantasy",
    related: "lotr",
    related_id: "2",
    director: "Peter Jackson",
    actors: [
      { id: 1, actor: "Martin Freeman" },
      { id: 2, actor: "Ian McKellen" },
      { id: 3, actor: "Richard Armitage" },
      { id: 4, actor: "Benedict Cumberbatch" },
      { id: 5, actor: "Orlando Bloom" },
    ],
  },
  {
    poster:
      "/images/Movies/Posters/07.03_The Hobbit - The Battle of the Five Armies.jpg",
    id: "7.03",
    title: "The Hobbit - The Battle of the Five Armies",
    rating: 7.4,
    year: 2014,
    category: "Fantasy",
    related: "lotr",
    related_id: "3",
    director: "Peter Jackson",
    actors: [
      { id: 1, actor: "Martin Freeman" },
      { id: 2, actor: "Ian McKellen" },
      { id: 3, actor: "Richard Armitage" },
      { id: 4, actor: "Luke Evans" },
      { id: 5, actor: "Evangeline Lilly" },
    ],
  },
  {
    poster: "/images/Movies/Posters/07.04_The Lord of the Rings 1.jpg",
    id: "7.04",
    title: "The Lord of the Rings - The Fellowship of the Ring",
    rating: 8.8,
    year: 2001,
    category: "Fantasy",
    related: "lotr",
    related_id: "4",
    director: "Peter Jackson",
    actors: [
      { id: 1, actor: "Elijah Wood" },
      { id: 2, actor: "Ian McKellen" },
      { id: 3, actor: "Viggo Mortensen" },
      { id: 4, actor: "Orlando Bloom" },
      { id: 5, actor: "Sean Astin" },
    ],
  },
  {
    poster: "/images/Movies/Posters/07.05_The Lord of the Rings 2.jpg",
    id: "7.05",
    title: "The Lord of the Rings - The Two Towers",
    rating: 8.8,
    year: 2002,
    category: "Fantasy",
    related: "lotr",
    related_id: "5",
    director: "Peter Jackson",
    actors: [
      { id: 1, actor: "Elijah Wood" },
      { id: 2, actor: "Ian McKellen" },
      { id: 3, actor: "Viggo Mortensen" },
      { id: 4, actor: "Orlando Bloom" },
      { id: 5, actor: "Sean Astin" },
    ],
  },
  {
    poster: "/images/Movies/Posters/07.06_The Lord of the Rings 3.jpg",
    id: "7.06",
    title: "The Lord of the Rings - The Return of the King",
    rating: 9.0,
    year: 2003,
    category: "Fantasy",
    related: "lotr",
    related_id: "6",
    director: "Peter Jackson",
    actors: [
      { id: 1, actor: "Elijah Wood" },
      { id: 2, actor: "Ian McKellen" },
      { id: 3, actor: "Viggo Mortensen" },
      { id: 4, actor: "Orlando Bloom" },
      { id: 5, actor: "Sean Astin" },
    ],
  },
  {
    poster: "/images/Movies/Posters/08_Pulp Fiction.jpg",
    id: "8",
    title: "Pulp Fiction",
    rating: 8.9,
    year: 1994,
    category: "Drama",
    related: "pulp_fiction",
    related_id: "1",
    director: "Quentin Tarantino",
    actors: [
      { id: 1, actor: "John Travolta" },
      { id: 2, actor: "Uma Thurman" },
      { id: 3, actor: "Samuel L. Jackson" },
      { id: 4, actor: "Bruce Willis" },
      { id: 5, actor: "Ving Rhames" },
    ],
  },
  {
    poster: "/images/Movies/Posters/09_The good, the bad and the ugly.jpg",
    id: "9",
    title: "The Good, the Bad and the Ugly",
    rating: 8.8,
    year: 1966,
    category: "Western",
    related: "Sergio Leone TGTBATU",
    related_id: "1",
    director: "Sergio Leone",
    actors: [
      { id: 1, actor: "Clint Eastwood" },
      { id: 2, actor: "Eli Wallach" },
      { id: 3, actor: "Lee Van Cleef" },
      { id: 4, actor: "Aldo Giuffrè" },
      { id: 5, actor: "Luigi Pistilli" },
    ],
  },
  {
    poster: "/images/Movies/Posters/10_Forrest Gump.jpg",
    id: "10",
    title: "Forrest Gump",
    rating: 8.8,
    year: 1994,
    category: "Drama",
    related: "forest_gump",
    related_id: "1",
    director: "Robert Zemeckis",
    actors: [
      { id: 1, actor: "Tom Hanks" },
      { id: 2, actor: "Robin Wright" },
      { id: 3, actor: "Gary Sinise" },
      { id: 4, actor: "Sally Field" },
      { id: 5, actor: "Mykelti Williamson" },
    ],
  },
  {
    poster: "/images/Movies/Posters/11_Fight Club.jpg",
    id: "11",
    title: "Fight Club",
    rating: 8.8,
    year: 1999,
    category: "Mind Fuck",
    related: "fight_club",
    related_id: "1",
    director: "David Fincher",
    actors: [
      { id: 1, actor: "Brad Pitt" },
      { id: 2, actor: "Edward Norton" },
      { id: 3, actor: "Helena Bonham Carter" },
      { id: 4, actor: "Meat Loaf" },
      { id: 5, actor: "Jared Leto" },
    ],
  },
  {
    poster: "/images/Movies/Posters/12_Inception.jpg",
    id: "12",
    title: "Inception",
    rating: 8.8,
    year: 2010,
    category: "Mind Fuck",
    related: "inception",
    related_id: "1",
    director: "Christopher Nolan",
    actors: [
      { id: 1, actor: "Leonardo DiCaprio" },
      { id: 2, actor: "Joseph Gordon-Levitt" },
      { id: 3, actor: "Elliot Page" },
      { id: 4, actor: "Tom Hardy" },
      { id: 5, actor: "Ken Watanabe" },
    ],
  },
  {
    poster: "/images/Movies/Posters/15.01_Star Wars - The Phantom Menace.jpg",
    id: "15.01",
    title: "Star Wars - The Phantom Menace",
    rating: 6.5,
    year: 1999,
    category: "SF",
    related: "star_wars",
    related_id: 1,
    director: "George Lucas",
    actors: [
      { id: 1, actor: "Liam Neeson" },
      { id: 2, actor: "Ewan McGregor" },
      { id: 3, actor: "Natalie Portman" },
      { id: 4, actor: "Jake Lloyd" },
      { id: 5, actor: "Ian McDiarmid" },
    ],
  },
  {
    poster: "/images/Movies/Posters/15.02_Star Wars - Attack of the Clones.jpg",
    id: "15.02",
    title: "Star Wars - Attack of the Clones",
    rating: 6.6,
    year: 2002,
    category: "SF",
    related: "star_wars",
    related_id: 2,
    director: "George Lucas",
    actors: [
      { id: 1, actor: "Ewan McGregor" },
      { id: 2, actor: "Natalie Portman" },
      { id: 3, actor: "Hayden Christensen" },
      { id: 4, actor: "Christopher Lee" },
      { id: 5, actor: "Samuel L. Jackson" },
    ],
  },
  {
    poster: "/images/Movies/Posters/15.03_Star Wars - Revenge of the Sith.jpg",
    id: "15.03",
    title: "Star Wars - Revenge of the Sith",
    rating: 7.5,
    year: 2005,
    category: "SF",
    related: "star_wars",
    related_id: 3,
    director: "George Lucas",
    actors: [
      { id: 1, actor: "Ewan McGregor" },
      { id: 2, actor: "Natalie Portman" },
      { id: 3, actor: "Hayden Christensen" },
      { id: 4, actor: "Ian McDiarmid" },
      { id: 5, actor: "Samuel L. Jackson" },
    ],
  },
  {
    poster: "/images/Movies/Posters/15.04_Star Wars - Rogue One.jpg",
    id: "15.04",
    title: "Star Wars - Rogue One",
    rating: 7.8,
    year: 2016,
    category: "SF",
    related: "star_wars",
    related_id: 4,
    director: "Gareth Edwards",
    actors: [
      { id: 1, actor: "Felicity Jones" },
      { id: 2, actor: "Diego Luna" },
      { id: 3, actor: "Alan Tudyk" },
      { id: 4, actor: "Donnie Yen" },
      { id: 5, actor: "Mads Mikkelsen" },
    ],
  },
  {
    poster: "/images/Movies/Posters/15.05_Star Wars - Solo.jpg",
    id: "15.05",
    title: "Star Wars - Solo",
    rating: 6.9,
    year: 2018,
    category: "SF",
    related: "star_wars",
    related_id: 5,
    director: "Ron Howard",
    actors: [
      { id: 1, actor: "Alden Ehrenreich" },
      { id: 2, actor: "Woody Harrelson" },
      { id: 3, actor: "Emilia Clarke" },
      { id: 4, actor: "Donald Glover" },
      { id: 5, actor: "Thandiwe Newton" },
    ],
  },
  {
    poster: "/images/Movies/Posters/15.06_Star Wars - A New Hope.jpg",
    id: "15.06",
    title: "Star Wars - A New Hope",
    rating: 8.6,
    year: 1977,
    category: "SF",
    related: "star_wars",
    related_id: 6,
    director: "George Lucas",
    actors: [
      { id: 1, actor: "Mark Hamill" },
      { id: 2, actor: "Harrison Ford" },
      { id: 3, actor: "Carrie Fisher" },
      { id: 4, actor: "Peter Cushing" },
      { id: 5, actor: "Alec Guinness" },
    ],
  },
  {
    poster:
      "/images/Movies/Posters/15.07_Star Wars - The Empire Strikes Back.jpg",
    id: "15.07",
    title: "Star Wars - The Empire Strikes Back",
    rating: 8.7,
    year: 1980,
    category: "SF",
    related: "star_wars",
    related_id: 7,
    director: "Irvin Kershner",
    actors: [
      { id: 1, actor: "Mark Hamill" },
      { id: 2, actor: "Harrison Ford" },
      { id: 3, actor: "Carrie Fisher" },
      { id: 4, actor: "Billy Dee Williams" },
      { id: 5, actor: "Anthony Daniels" },
    ],
  },
  {
    poster: "/images/Movies/Posters/15.08_Star Wars - Return of the Jedi.jpg",
    id: "15.08",
    title: "Star Wars - Return of the Jedi",
    rating: 8.3,
    year: 1983,
    category: "SF",
    related: "star_wars",
    related_id: 8,
    director: "Richard Marquand",
    actors: [
      { id: 1, actor: "Mark Hamill" },
      { id: 2, actor: "Harrison Ford" },
      { id: 3, actor: "Carrie Fisher" },
      { id: 4, actor: "Billy Dee Williams" },
      { id: 5, actor: "Anthony Daniels" },
    ],
  },
  {
    poster: "/images/Movies/Posters/15.09_Star Wars - The Force Awakens.jpg",
    id: "15.09",
    title: "Star Wars - The Force Awakens",
    rating: 7.9,
    year: 2015,
    category: "SF",
    related: "star_wars",
    related_id: 9,
    director: "J.J. Abrams",
    actors: [
      { id: 1, actor: "Harrison Ford" },
      { id: 2, actor: "Mark Hamill" },
      { id: 3, actor: "Carrie Fisher" },
      { id: 4, actor: "Adam Driver" },
      { id: 5, actor: "Daisy Ridley" },
    ],
  },
  {
    poster: "/images/Movies/Posters/15.10_Star Wars - The Last Jedi.jpg",
    id: "15.10",
    title: "Star Wars - The Last Jedi",
    rating: 7.0,
    year: 2017,
    category: "SF",
    related: "star_wars",
    related_id: 10,
    director: "Rian Johnson",
    actors: [
      { id: 1, actor: "Mark Hamill" },
      { id: 2, actor: "Carrie Fisher" },
      { id: 3, actor: "Adam Driver" },
      { id: 4, actor: "Daisy Ridley" },
      { id: 5, actor: "John Boyega" },
    ],
  },
  {
    poster:
      "/images/Movies/Posters/15.11_Star Wars - The Rise of Skywalker.jpg",
    id: "15.11",
    title: "Star Wars - The Rise of Skywalker",
    rating: 6.5,
    year: 2019,
    category: "SF",
    related: "star_wars",
    related_id: 11,
    director: "J.J. Abrams",
    actors: [
      { id: 1, actor: "Carrie Fisher" },
      { id: 2, actor: "Mark Hamill" },
      { id: 3, actor: "Adam Driver" },
      { id: 4, actor: "Daisy Ridley" },
      { id: 5, actor: "John Boyega" },
    ],
  },
  {
    poster: "/images/Movies/Posters/16.01_The Matrix 1.jpg",
    id: "16.01",
    title: "The Matrix",
    rating: 8.7,
    year: 1999,
    category: "post-apocalyptic",
    related: "matrix",
    related_id: 1,
    director: "Lana Wachowski, Lilly Wachowski",
    actors: [
      { id: 1, actor: "Keanu Reeves" },
      { id: 2, actor: "Laurence Fishburne" },
      { id: 3, actor: "Carrie-Anne Moss" },
      { id: 4, actor: "Hugo Weaving" },
      { id: 5, actor: "Gloria Foster" },
    ],
  },
  {
    poster: "/images/Movies/Posters/16.02_The Matrix Reloaded.jpg",
    id: "16.02",
    title: "The Matrix Reloaded",
    rating: 7.2,
    year: 2003,
    category: "post-apocalyptic",
    related: "matrix",
    related_id: 2,
    director: "Lana Wachowski, Lilly Wachowski",
    actors: [
      { id: 1, actor: "Keanu Reeves" },
      { id: 2, actor: "Laurence Fishburne" },
      { id: 3, actor: "Carrie-Anne Moss" },
      { id: 4, actor: "Hugo Weaving" },
      { id: 5, actor: "Jada Pinkett Smith" },
    ],
  },
  {
    poster: "/images/Movies/Posters/16.03_The Matrix Revolutions.jpg",
    id: "16.03",
    title: "The Matrix Revolutions",
    rating: 6.8,
    year: 2003,
    category: "post-apocalyptic",
    related: "matrix",
    related_id: 3,
    director: "Lana Wachowski, Lilly Wachowski",
    actors: [
      { id: 1, actor: "Keanu Reeves" },
      { id: 2, actor: "Laurence Fishburne" },
      { id: 3, actor: "Carrie-Anne Moss" },
      { id: 4, actor: "Hugo Weaving" },
      { id: 5, actor: "Jada Pinkett Smith" },
    ],
  },
  {
    poster: "/images/Movies/Posters/16.04_The Matrix Resurrections.jpg",
    id: "16.04",
    title: "The Matrix Resurrections",
    rating: 5.7,
    year: 2021,
    category: "post-apocalyptic",
    related: "matrix",
    related_id: 4,
    director: "Lana Wachowski",
    actors: [
      { id: 1, actor: "Keanu Reeves" },
      { id: 2, actor: "Carrie-Anne Moss" },
      { id: 3, actor: "Yahya Abdul-Mateen II" },
      { id: 4, actor: "Jessica Henwick" },
      { id: 5, actor: "Neil Patrick Harris" },
    ],
  },
  {
    poster: "/images/Movies/Posters/17_Goodfellas.jpg",
    id: "17",
    title: "Goodfellas",
    rating: 8.7,
    year: 1990,
    category: "Mafia",
    related: "goodfellas",
    related_id: 1,
    director: "Martin Scorsese",
    actors: [
      { id: 1, actor: "Robert De Niro" },
      { id: 2, actor: "Ray Liotta" },
      { id: 3, actor: "Joe Pesci" },
      { id: 4, actor: "Lorraine Bracco" },
      { id: 5, actor: "Paul Sorvino" },
    ],
  },
  {
    poster: "/images/Movies/Posters/18.01_Dune 1.jpg",
    id: "18.01",
    title: "Dune",
    rating: 8.2,
    year: 2021,
    category: "SF",
    related: "dune",
    related_id: 1,
    director: "Denis Villeneuve",
    actors: [
      { id: 1, actor: "Timothée Chalamet" },
      { id: 2, actor: "Rebecca Ferguson" },
      { id: 3, actor: "Oscar Isaac" },
      { id: 4, actor: "Josh Brolin" },
      { id: 5, actor: "Stellan Skarsgård" },
    ],
  },
  {
    poster: "/images/Movies/Posters/18.02_Dune 2.jpg",
    id: "18.02",
    title: "Dune: Part Two",
    rating: 8.4,
    year: 2023,
    category: "SF",
    related: "dune",
    related_id: 2,
    director: "Denis Villeneuve",
    actors: [
      { id: 1, actor: "Timothée Chalamet" },
      { id: 2, actor: "Rebecca Ferguson" },
      { id: 3, actor: "Zendaya" },
      { id: 4, actor: "Javier Bardem" },
      { id: 5, actor: "Dave Bautista" },
    ],
  },
  {
    poster: "/images/Movies/Posters/19_One Flew over the Cuckoo's Nest.jpg",
    id: "19",
    title: "One Flew Over the Cuckoo's Nest",
    rating: 8.7,
    year: 1975,
    category: "Drama",
    related: "one_flew_over_the_cuckoos_nest",
    related_id: 1,
    director: "Milos Forman",
    actors: [
      { id: 1, actor: "Jack Nicholson" },
      { id: 2, actor: "Louise Fletcher" },
      { id: 3, actor: "Will Sampson" },
      { id: 4, actor: "Brad Dourif" },
      { id: 5, actor: "Danny DeVito" },
    ],
  },
  {
    poster: "/images/Movies/Posters/20_Seven.jpg",
    id: "20",
    title: "Se7en",
    rating: 8.6,
    year: 1995,
    category: "Mind Fuck",
    related: "seven",
    related_id: 1,
    director: "David Fincher",
    actors: [
      { id: 1, actor: "Brad Pitt" },
      { id: 2, actor: "Morgan Freeman" },
      { id: 3, actor: "Gwyneth Paltrow" },
      { id: 4, actor: "Kevin Spacey" },
      { id: 5, actor: "R. Lee Ermey" },
    ],
  },
  {
    poster: "/images/Movies/Posters/21_Interstellar.jpg",
    id: "21",
    title: "Interstellar",
    rating: 8.6,
    year: 2014,
    category: "SF",
    related: "interstellar",
    related_id: 1,
    director: "Christopher Nolan",
    actors: [
      { id: 1, actor: "Matthew McConaughey" },
      { id: 2, actor: "Anne Hathaway" },
      { id: 3, actor: "Jessica Chastain" },
      { id: 4, actor: "Bill Irwin" },
      { id: 5, actor: "Ellen Burstyn" },
    ],
  },
  {
    poster: "/images/Movies/Posters/23_The Silence of the Lambs.jpg",
    id: "23",
    title: "The Silence of the Lambs",
    rating: 8.6,
    year: 1991,
    category: "Mind Fuck",
    related: "silence_of_the_lambs",
    related_id: 1,
    director: "Jonathan Demme",
    actors: [
      { id: 1, actor: "Jodie Foster" },
      { id: 2, actor: "Anthony Hopkins" },
      { id: 3, actor: "Scott Glenn" },
      { id: 4, actor: "Ted Levine" },
      { id: 5, actor: "Anthony Heald" },
    ],
  },
  {
    poster: "/images/Movies/Posters/24_Saving Private Ryan.jpg",
    id: "24",
    title: "Saving Private Ryan",
    rating: 8.6,
    year: 1998,
    category: "War",
    related: "saving_private_ryan",
    related_id: 1,
    director: "Steven Spielberg",
    actors: [
      { id: 1, actor: "Tom Hanks" },
      { id: 2, actor: "Matt Damon" },
      { id: 3, actor: "Tom Sizemore" },
      { id: 4, actor: "Edward Burns" },
      { id: 5, actor: "Barry Pepper" },
    ],
  },
  {
    poster: "/images/Movies/Posters/25.01_City of God.jpg",
    id: "25.01",
    title: "City of God",
    rating: 8.6,
    year: 2002,
    category: "Drama",
    related: "city_of_god",
    related_id: 1,
    director: "Fernando Meirelles",
    actors: [
      { id: 1, actor: "Alexandre Rodrigues" },
      { id: 2, actor: "Leandro Firmino" },
      { id: 3, actor: "Phellipe Haagensen" },
      { id: 4, actor: "Douglas Silva" },
      { id: 5, actor: "Jonathan Haagensen" },
    ],
  },
  {
    poster: "/images/Movies/Posters/25.02_Elite Squad 1.jpg",
    id: "25.02",
    title: "Elite Squad",
    rating: 8.1,
    year: 2007,
    category: "Action",
    related: "city_of_god",
    related_id: 2,
    director: "José Padilha",
    actors: [
      { id: 1, actor: "Wagner Moura" },
      { id: 2, actor: "André Ramiro" },
      { id: 3, actor: "Caio Junqueira" },
      { id: 4, actor: "Milhem Cortaz" },
      { id: 5, actor: "Fernanda Machado" },
    ],
  },
  {
    poster: "/images/Movies/Posters/25.03_Elite Squad 2.jpg",
    id: "25.03",
    title: "Elite Squad: The Enemy Within",
    rating: 8.0,
    year: 2010,
    category: "Action",
    related: "city_of_god",
    related_id: 3,
    director: "José Padilha",
    actors: [
      { id: 1, actor: "Wagner Moura" },
      { id: 2, actor: "Irandhir Santos" },
      { id: 3, actor: "André Ramiro" },
      { id: 4, actor: "Milhem Cortaz" },
      { id: 5, actor: "Sandro Rocha" },
    ],
  },
  {
    poster: "/images/Movies/Posters/27_Life is Beautiful.jpg",
    id: 27,
    title: "Life is Beautiful",
    rating: 8.6,
    year: 1997,
    category: "War",
    related: "life_is_beautiful",
    related_id: 1,
    director: "Roberto Benigni",
    actors: [
      { id: 1, actor: "Roberto Benigni" },
      { id: 2, actor: "Nicoletta Braschi" },
      { id: 3, actor: "Giorgio Cantarini" },
      { id: 4, actor: "Giustino Durano" },
      { id: 5, actor: "Sergio Bini Bustric" },
    ],
  },
  {
    poster: "/images/Movies/Posters/28_The Green Mile.jpg",
    id: 28,
    title: "The Green Mile",
    rating: 8.6,
    year: 1999,
    category: "Drama",
    related: "green_mile",
    related_id: 1,
    director: "Frank Darabont",
    actors: [
      { id: 1, actor: "Tom Hanks" },
      { id: 2, actor: "Michael Clarke Duncan" },
      { id: 3, actor: "David Morse" },
      { id: 4, actor: "Bonnie Hunt" },
      { id: 5, actor: "James Cromwell" },
    ],
  },
  {
    poster: "/images/Movies/Posters/29.01_The Terminator 1.jpg",
    id: "29.01",
    title: "The Terminator",
    rating: 8.3,
    year: 1984,
    category: "SF",
    related: "Terminator",
    related_id: 1,
    director: "James Cameron",
    actors: [
      { id: 1, actor: "Arnold Schwarzenegger" },
      { id: 2, actor: "Linda Hamilton" },
      { id: 3, actor: "Michael Biehn" },
      { id: 4, actor: "Paul Winfield" },
      { id: 5, actor: "Lance Henriksen" },
    ],
  },
  {
    poster: "/images/Movies/Posters/29.02_Terminator 2 - Judgment Day.jpg",
    id: "29.02",
    title: "Terminator 2 - Judgment Day",
    rating: 8.6,
    year: 1991,
    category: "SF",
    related: "Terminator",
    related_id: 2,
    director: "James Cameron",
    actors: [
      { id: 1, actor: "Arnold Schwarzenegger" },
      { id: 2, actor: "Linda Hamilton" },
      { id: 3, actor: "Edward Furlong" },
      { id: 4, actor: "Robert Patrick" },
      { id: 5, actor: "Joe Morton" },
    ],
  },
  {
    poster:
      "/images/Movies/Posters/29.03_Terminator 3 - Rise of the Machines.jpg",
    id: "29.03",
    title: "Terminator 3- Rise of the Machines",
    rating: 6.3,
    year: 2003,
    category: "SF",
    related: "Terminator",
    related_id: 3,
    director: "Jonathan Mostow",
    actors: [
      { id: 1, actor: "Arnold Schwarzenegger" },
      { id: 2, actor: "Nick Stahl" },
      { id: 3, actor: "Claire Danes" },
      { id: 4, actor: "Kristanna Loken" },
      { id: 5, actor: "David Andrews" },
    ],
  },
  {
    poster: "/images/Movies/Posters/29.04_Terminator Salvation.jpg",
    id: "29.04",
    title: "Terminator Salvation",
    rating: 6.5,
    year: 2009,
    category: "SF",
    related: "Terminator",
    related_id: 4,
    director: "McG",
    actors: [
      { id: 1, actor: "Christian Bale" },
      { id: 2, actor: "Sam Worthington" },
      { id: 3, actor: "Anton Yelchin" },
      { id: 4, actor: "Moon Bloodgood" },
      { id: 5, actor: "Bryce Dallas Howard" },
    ],
  },
  {
    poster: "/images/Movies/Posters/29.05_Terminator Genisys.jpg",
    id: "29.05",
    title: "Terminator Genisys",
    rating: 6.3,
    year: 2015,
    category: "SF",
    related: "Terminator",
    related_id: 5,
    director: "Alan Taylor",
    actors: [
      { id: 1, actor: "Arnold Schwarzenegger" },
      { id: 2, actor: "Emilia Clarke" },
      { id: 3, actor: "Jai Courtney" },
      { id: 4, actor: "Jason Clarke" },
      { id: 5, actor: "J.K. Simmons" },
    ],
  },
  {
    poster: "/images/Movies/Posters/29.06_Terminator Dark Fate.jpg",
    id: "29.06",
    title: "Terminator Dark Fate",
    rating: 6.2,
    year: 2019,
    category: "Action-Sci-Fi",
    related: "Terminator",
    related_id: 6,
    director: "Tim Miller",
    actors: [
      { id: 1, actor: "Linda Hamilton" },
      { id: 2, actor: "Arnold Schwarzenegger" },
      { id: 3, actor: "Mackenzie Davis" },
      { id: 4, actor: "Natalia Reyes" },
      { id: 5, actor: "Gabriel Luna" },
    ],
  },
  {
    poster: "/images/Movies/Posters/31.01_Back to the Future 1.jpg",
    id: "31.01",
    title: "Back to the Future",
    rating: 8.5,
    year: 1985,
    category: "SF",
    related: "Back to the Future",
    related_id: 1,
    director: "Robert Zemeckis",
    actors: [
      { id: 1, actor: "Michael J. Fox" },
      { id: 2, actor: "Christopher Lloyd" },
      { id: 3, actor: "Lea Thompson" },
      { id: 4, actor: "Crispin Glover" },
      { id: 5, actor: "Thomas F. Wilson" },
    ],
  },
  {
    poster: "/images/Movies/Posters/31.02_Back to the Future 2.jpg",
    id: "31.02",
    title: "Back to the Future Part II",
    rating: 7.8,
    year: 1989,
    category: "SF",
    related: "Back to the Future",
    related_id: 2,
    director: "Robert Zemeckis",
    actors: [
      { id: 1, actor: "Michael J. Fox" },
      { id: 2, actor: "Christopher Lloyd" },
      { id: 3, actor: "Lea Thompson" },
      { id: 4, actor: "Thomas F. Wilson" },
      { id: 5, actor: "Elisabeth Shue" },
    ],
  },
  {
    poster: "/images/Movies/Posters/31.03_Back to the Future 3.jpg",
    id: "31.03",
    title: "Back to the Future Part III",
    rating: 7.4,
    year: 1990,
    category: "SF",
    related: "Back to the Future",
    related_id: 3,
    director: "Robert Zemeckis",
    actors: [
      { id: 1, actor: "Michael J. Fox" },
      { id: 2, actor: "Christopher Lloyd" },
      { id: 3, actor: "Mary Steenburgen" },
      { id: 4, actor: "Thomas F. Wilson" },
      { id: 5, actor: "Lea Thompson" },
    ],
  },
  {
    poster: "/images/Movies/Posters/32_Spirited Away.jpg",
    id: "32",
    title: "Spirited Away",
    rating: 8.6,
    year: 2001,
    category: "Animation",
    related: "Spirited Away",
    related_id: 1,
    director: "Hayao Miyazaki",
    actors: [
      { id: 1, actor: "Rumi Hiiragi" },
      { id: 2, actor: "Miyu Irino" },
      { id: 3, actor: "Mari Natsuki" },
      { id: 4, actor: "Takashi Naito" },
      { id: 5, actor: "Yasuko Sawaguchi" },
    ],
  },
  {
    poster: "/images/Movies/Posters/33_The Pianist.jpg",
    id: "33",
    title: "The Pianist",
    rating: 8.5,
    year: 2002,
    category: "War",
    related: "The Pianist",
    related_id: 1,
    director: "Roman Polanski",
    actors: [
      { id: 1, actor: "Adrien Brody" },
      { id: 2, actor: "Thomas Kretschmann" },
      { id: 3, actor: "Frank Finlay" },
      { id: 4, actor: "Maureen Lipman" },
      { id: 5, actor: "Emilia Fox" },
    ],
  },
  {
    poster: "/images/Movies/Posters/34_Parasite.jpg",
    id: "34",
    title: "Parasite",
    rating: 8.6,
    year: 2019,
    category: "Drama",
    related: "Parasite",
    related_id: 1,
    director: "Bong Joon Ho",
    actors: [
      { id: 1, actor: "Kang-ho Song" },
      { id: 2, actor: "Sun-kyun Lee" },
      { id: 3, actor: "Yeo-jeong Jo" },
      { id: 4, actor: "Woo-sik Choi" },
      { id: 5, actor: "So-dam Park" },
    ],
  },
  {
    poster: "/images/Movies/Posters/37_Gladiator.jpg",
    id: "37",
    title: "Gladiator",
    rating: 8.5,
    year: 2000,
    category: "History",
    related: "Gladiator",
    related_id: 1,
    director: "Ridley Scott",
    actors: [
      { id: 1, actor: "Russell Crowe" },
      { id: 2, actor: "Joaquin Phoenix" },
      { id: 3, actor: "Connie Nielsen" },
      { id: 4, actor: "Oliver Reed" },
      { id: 5, actor: "Richard Harris" },
    ],
  },
  {
    poster: "/images/Movies/Posters/39_Leon.jpg",
    id: "39",
    title: "Léon: The Professional",
    rating: 8.5,
    year: 1994,
    category: "Action-Crime",
    related: "Léon: The Professional",
    related_id: 1,
    director: "Luc Besson",
    actors: [
      { id: 1, actor: "Jean Reno" },
      { id: 2, actor: "Gary Oldman" },
      { id: 3, actor: "Natalie Portman" },
      { id: 4, actor: "Danny Aiello" },
      { id: 5, actor: "Peter Appel" },
    ],
  },
  {
    poster: "/images/Movies/Posters/40_The Departed.jpg",
    id: "40",
    title: "The Departed",
    rating: 8.5,
    year: 2006,
    category: "Mafia",
    related: "The Departed",
    related_id: 1,
    director: "Martin Scorsese",
    actors: [
      { id: 1, actor: "Leonardo DiCaprio" },
      { id: 2, actor: "Matt Damon" },
      { id: 3, actor: "Jack Nicholson" },
      { id: 4, actor: "Mark Wahlberg" },
      { id: 5, actor: "Martin Sheen" },
    ],
  },
  {
    poster: "/images/Movies/Posters/41_American History X.jpg",
    id: "41",
    title: "American History X",
    rating: 8.5,
    year: 1998,
    category: "Drama",
    related: "American History X",
    related_id: 1,
    director: "Tony Kaye",
    actors: [
      { id: 1, actor: "Edward Norton" },
      { id: 2, actor: "Edward Furlong" },
      { id: 3, actor: "Beverly D'Angelo" },
      { id: 4, actor: "Avery Brooks" },
      { id: 5, actor: "Ethan Suplee" },
    ],
  },
  {
    poster: "/images/Movies/Posters/42_Whiplash.jpg",
    id: "42",
    title: "Whiplash",
    rating: 8.5,
    year: 2014,
    category: "Music",
    related: "Whiplash",
    related_id: 1,
    director: "Damien Chazelle",
    actors: [
      { id: 1, actor: "Miles Teller" },
      { id: 2, actor: "J.K. Simmons" },
      { id: 3, actor: "Paul Reiser" },
      { id: 4, actor: "Melissa Benoist" },
      { id: 5, actor: "Austin Stowell" },
    ],
  },
  {
    poster: "/images/Movies/Posters/43_The Prestige.jpg",
    id: "43",
    title: "The Prestige",
    rating: 8.5,
    year: 2006,
    category: "Mind Fuck",
    related: "The Prestige",
    related_id: 1,
    director: "Christopher Nolan",
    actors: [
      { id: 1, actor: "Christian Bale" },
      { id: 2, actor: "Hugh Jackman" },
      { id: 3, actor: "Scarlett Johansson" },
      { id: 4, actor: "Michael Caine" },
      { id: 5, actor: "Piper Perabo" },
    ],
  },
  {
    poster: "/images/Movies/Posters/44_Grave of the Fireflies.jpg",
    id: "44",
    title: "Grave of the Fireflies",
    rating: 8.5,
    year: 1988,
    category: "Animation",
    related: "Grave of the Fireflies",
    related_id: 1,
    director: "Isao Takahata",
    actors: [
      { id: 1, actor: "Tsutomu Tatsumi" },
      { id: 2, actor: "Ayano Shiraishi" },
      { id: 3, actor: "Yoshiko Shinohara" },
      { id: 4, actor: "Akemi Yamaguchi" },
      { id: 5, actor: "Tadashi Nakamura" },
    ],
  },
  {
    poster: "/images/Movies/Posters/46_The Usual Suspects.jpg",
    id: "46",
    title: "The Usual Suspects",
    rating: 8.5,
    year: 1995,
    category: "Mind Fuck",
    related: "The Usual Suspects",
    related_id: 1,
    director: "Bryan Singer",
    actors: [
      { id: 1, actor: "Kevin Spacey" },
      { id: 2, actor: "Gabriel Byrne" },
      { id: 3, actor: "Chazz Palminteri" },
      { id: 4, actor: "Stephen Baldwin" },
      { id: 5, actor: "Benicio Del Toro" },
    ],
  },
  {
    poster: "/images/Movies/Posters/48_The Intouchables.jpg",
    id: "48",
    title: "The Intouchables",
    rating: 8.5,
    year: 2011,
    category: "Drama",
    related: "The Intouchables",
    related_id: 1,
    director: "Olivier Nakache",
    actors: [
      { id: 1, actor: "François Cluzet" },
      { id: 2, actor: "Omar Sy" },
      { id: 3, actor: "Anne Le Ny" },
      { id: 4, actor: "Audrey Fleurot" },
      { id: 5, actor: "Joséphine de Meaux" },
    ],
  },
  {
    poster: "/images/Movies/Posters/49_Cinema Paradiso.jpg",
    id: "49",
    title: "Cinema Paradiso",
    rating: 8.5,
    year: 1988,
    category: "Drama",
    related: "Cinema Paradiso",
    related_id: 1,
    director: "Giuseppe Tornatore",
    actors: [
      { id: 1, actor: "Philippe Noiret" },
      { id: 2, actor: "Enzo Cannavale" },
      { id: 3, actor: "Antonella Attili" },
      { id: 4, actor: "Isa Danieli" },
      { id: 5, actor: "Pupella Maggio" },
    ],
  },
  {
    poster: "/images/Movies/Posters/52_Once Upon a Time in the West.jpg",
    id: "52",
    title: "Once Upon a Time in the West",
    rating: 8.5,
    year: 1968,
    category: "Western",
    related: "Once Upon a Time in the West",
    related_id: 1,
    director: "Sergio Leone",
    actors: [
      { id: 1, actor: "Henry Fonda" },
      { id: 2, actor: "Charles Bronson" },
      { id: 3, actor: "Claudia Cardinale" },
      { id: 4, actor: "Jason Robards" },
      { id: 5, actor: "Gabriele Ferzetti" },
    ],
  },
  {
    poster: "/images/Movies/Posters/53.01_Prometheus.jpg",
    id: "53.01",
    title: "Prometheus",
    rating: 7.0,
    year: 2012,
    category: "SF",
    related: "Alien",
    related_id: 1,
    director: "Ridley Scott",
    actors: [
      { id: 1, actor: "Noomi Rapace" },
      { id: 2, actor: "Logan Marshall-Green" },
      { id: 3, actor: "Michael Fassbender" },
      { id: 4, actor: "Charlize Theron" },
      { id: 5, actor: "Idris Elba" },
    ],
  },
  {
    poster: "/images/Movies/Posters/53.02_Alien Covenant.jpg",
    id: "53.02",
    title: "Alien Covenant",
    rating: 6.4,
    year: 2017,
    category: "SF",
    related: "Alien",
    related_id: 2,
    director: "Ridley Scott",
    actors: [
      { id: 1, actor: "Michael Fassbender" },
      { id: 2, actor: "Katherine Waterston" },
      { id: 3, actor: "Billy Crudup" },
      { id: 4, actor: "Danny McBride" },
      { id: 5, actor: "Demián Bichir" },
    ],
  },
  {
    poster: "/images/Movies/Posters/53.03_Alien.jpg",
    id: "53.03",
    title: "Alien",
    rating: 8.5,
    year: 1979,
    category: "SF",
    related: "Alien",
    related_id: 3,
    director: "Ridley Scott",
    actors: [
      { id: 1, actor: "Sigourney Weaver" },
      { id: 2, actor: "Tom Skerritt" },
      { id: 3, actor: "John Hurt" },
      { id: 4, actor: "Veronica Cartwright" },
      { id: 5, actor: "Harry Dean Stanton" },
    ],
  },
  {
    poster: "/images/Movies/Posters/53.04_Aliens.jpg",
    id: "53.04",
    title: "Aliens",
    rating: 8.4,
    year: 1986,
    category: "SF",
    related: "Alien",
    related_id: 4,
    director: "James Cameron",
    actors: [
      { id: 1, actor: "Sigourney Weaver" },
      { id: 2, actor: "Michael Biehn" },
      { id: 3, actor: "Carrie Henn" },
      { id: 4, actor: "Paul Reiser" },
      { id: 5, actor: "Bill Paxton" },
    ],
  },
  {
    poster: "/images/Movies/Posters/53.05_Alien 3.jpg",
    id: "53.05",
    title: "Alien 3",
    rating: 6.4,
    year: 1992,
    category: "SF",
    related: "Alien",
    related_id: 5,
    director: "David Fincher",
    actors: [
      { id: 1, actor: "Sigourney Weaver" },
      { id: 2, actor: "Charles S. Dutton" },
      { id: 3, actor: "Charles Dance" },
      { id: 4, actor: "Paul McGann" },
      { id: 5, actor: "Lance Henriksen" },
    ],
  },
  {
    poster: "/images/Movies/Posters/53.06_Alien Resurrection.jpg",
    id: "53.06",
    title: "Alien Resurrection",
    rating: 6.2,
    year: 1997,
    category: "SF",
    related: "Alien",
    related_id: 6,
    director: "Jean-Pierre Jeunet",
    actors: [
      { id: 1, actor: "Sigourney Weaver" },
      { id: 2, actor: "Winona Ryder" },
      { id: 3, actor: "Dominique Pinon" },
      { id: 4, actor: "Ron Perlman" },
      { id: 5, actor: "Gary Dourdan" },
    ],
  },
  {
    poster: "/images/Movies/Posters/55_Django Unchained.jpg",
    id: "55",
    title: "Django Unchained",
    rating: 8.3,
    year: 2012,
    category: "Western",
    related: "Django Unchained",
    related_id: 1,
    director: "Quentin Tarantino",
    actors: [
      { id: 1, actor: "Jamie Foxx" },
      { id: 2, actor: "Christoph Waltz" },
      { id: 3, actor: "Leonardo DiCaprio" },
      { id: 4, actor: "Kerry Washington" },
      { id: 5, actor: "Samuel L. Jackson" },
    ],
  },
  {
    poster: "/images/Movies/Posters/56_Apocalypse Now.jpg",
    id: "56",
    title: "Apocalypse Now",
    rating: 8.4,
    year: 1979,
    category: "War",
    related: "Apocalypse Now",
    related_id: 1,
    director: "Francis Ford Coppola",
    actors: [
      { id: 1, actor: "Martin Sheen" },
      { id: 2, actor: "Marlon Brando" },
      { id: 3, actor: "Robert Duvall" },
      { id: 4, actor: "Laurence Fishburne" },
      { id: 5, actor: "Dennis Hopper" },
    ],
  },
  {
    poster: "/images/Movies/Posters/57_Memento.jpg",
    id: "57",
    title: "Memento",
    rating: 8.4,
    year: 2000,
    category: "Mind Fuck",
    related: "Memento",
    related_id: 1,
    director: "Christopher Nolan",
    actors: [
      { id: 1, actor: "Guy Pearce" },
      { id: 2, actor: "Carrie-Anne Moss" },
      { id: 3, actor: "Joe Pantoliano" },
      { id: 4, actor: "Mark Boone Junior" },
      { id: 5, actor: "Stephen Tobolowsky" },
    ],
  },
  {
    poster:
      "/images/Movies/Posters/60.01_Indiana Jones - Raiders of the Lost Ark.jpg",
    id: "60.01",
    title: "Indiana Jones - Raiders of the Lost Ark",
    rating: 8.3,
    year: 1981,
    category: "Adventure",
    related: "indiana_jones",
    related_id: "1",
    director: "Steven Spielberg",
    actors: [
      { id: 1, actor: "Harrison Ford" },
      { id: 2, actor: "Karen Allen" },
      { id: 3, actor: "Paul Freeman" },
      { id: 4, actor: "Ronald Lacey" },
      { id: 5, actor: "John Rhys-Davies" },
    ],
  },
  {
    poster:
      "/images/Movies/Posters/60.02_Indiana Jones and the Temple of Doom.jpg",
    id: "60.02",
    title: "Indiana Jones and the Temple of Doom",
    rating: 7.6,
    year: 1984,
    category: "Adventure",
    related: "indiana_jones",
    related_id: "2",
    director: "Steven Spielberg",
    actors: [
      { id: 1, actor: "Harrison Ford" },
      { id: 2, actor: "Kate Capshaw" },
      { id: 3, actor: "Jonathan Ke Quan" },
      { id: 4, actor: "Amrish Puri" },
      { id: 5, actor: "Roshan Seth" },
    ],
  },
  {
    poster:
      "/images/Movies/Posters/60.03_Indiana Jones and the Last Crusade.jpg",
    id: "60.03",
    title: "Indiana Jones and the Last Crusade",
    rating: 8.2,
    year: 1989,
    category: "Adventure",
    related: "indiana_jones",
    related_id: "3",
    director: "Steven Spielberg",
    actors: [
      { id: 1, actor: "Harrison Ford" },
      { id: 2, actor: "Sean Connery" },
      { id: 3, actor: "Alison Doody" },
      { id: 4, actor: "Denholm Elliott" },
      { id: 5, actor: "Julian Glover" },
    ],
  },
  {
    poster:
      "/images/Movies/Posters/60.04_Indiana Jones and the Kingdom of the Crystal Skull.jpg",
    id: "60.04",
    title: "Indiana Jones and the Kingdom of the Crystal Skull",
    rating: 6.2,
    year: 2008,
    category: "Adventure",
    related: "indiana_jones",
    related_id: "4",
    director: "Steven Spielberg",
    actors: [
      { id: 1, actor: "Harrison Ford" },
      { id: 2, actor: "Shia LaBeouf" },
      { id: 3, actor: "Cate Blanchett" },
      { id: 4, actor: "Karen Allen" },
      { id: 5, actor: "Ray Winstone" },
    ],
  },
  {
    poster:
      "/images/Movies/Posters/60.05_Indiana Jones and the Dial of Destiny.jpg",
    id: "60.05",
    title: "Indiana Jones and the Dial of Destiny",
    rating: 6.7,
    year: 2023,
    category: "Adventure",
    related: "indiana_jones",
    related_id: "5",
    director: "James Mangold",
    actors: [
      { id: 1, actor: "Harrison Ford" },
      { id: 2, actor: "Phoebe Waller-Bridge" },
      { id: 3, actor: "Antonio Banderas" },
      { id: 4, actor: "Mads Mikkelsen" },
      { id: 5, actor: "Toby Jones" },
    ],
  },
  {
    poster: "/images/Movies/Posters/61_The Lives of Others.jpg",
    id: "61",
    title: "The Lives of Others",
    rating: 8.4,
    year: 2006,
    category: "Drama",
    related: "the_lives_of_others",
    related_id: 1,
    director: "Florian Henckel von Donnersmarck",
    actors: [
      { id: 1, actor: "Ulrich Mühe" },
      { id: 2, actor: "Sebastian Koch" },
      { id: 3, actor: "Martina Gedeck" },
      { id: 4, actor: "Hildegard Schroedter" },
      { id: 5, actor: "Hans-Uwe Bauer" },
    ],
  },
  {
    poster: "/images/Movies/Posters/64.01_The Avengers.jpg",
    id: "64.01",
    title: "The Avengers",
    rating: 8.0,
    year: 2012,
    category: "Super Hero",
    related: "Avengers",
    related_id: 1,
    director: "Joss Whedon",
    actors: [
      { id: 1, actor: "Robert Downey Jr." },
      { id: 2, actor: "Chris Evans" },
      { id: 3, actor: "Mark Ruffalo" },
      { id: 4, actor: "Chris Hemsworth" },
      { id: 5, actor: "Scarlett Johansson" },
    ],
  },
  {
    poster: "/images/Movies/Posters/64.02_The Avengers Age of Ultron.jpg",
    id: "64.02",
    title: "The Avengers: Age of Ultron",
    rating: 7.3,
    year: 2015,
    category: "Super Hero",
    related: "Avengers",
    related_id: 2,
    director: "Joss Whedon",
    actors: [
      { id: 1, actor: "Robert Downey Jr." },
      { id: 2, actor: "Chris Evans" },
      { id: 3, actor: "Mark Ruffalo" },
      { id: 4, actor: "Chris Hemsworth" },
      { id: 5, actor: "Scarlett Johansson" },
    ],
  },
  {
    poster: "/images/Movies/Posters/64.03_Avengers Infinity War.jpg",
    id: "64.03",
    title: "Avengers: Infinity War",
    rating: 8.4,
    year: 2018,
    category: "Super Hero",
    related: "Avengers",
    related_id: 3,
    director: "Anthony Russo, Joe Russo",
    actors: [
      { id: 1, actor: "Robert Downey Jr." },
      { id: 2, actor: "Chris Evans" },
      { id: 3, actor: "Mark Ruffalo" },
      { id: 4, actor: "Chris Hemsworth" },
      { id: 5, actor: "Scarlett Johansson" },
    ],
  },
  {
    poster: "/images/Movies/Posters/64.04_Avengers Endgame.jpg",
    id: "64.04",
    title: "Avengers: Endgame",
    rating: 8.4,
    year: 2019,
    category: "Super Hero",
    related: "Avengers",
    related_id: 4,
    director: "Anthony Russo, Joe Russo",
    actors: [
      { id: 1, actor: "Robert Downey Jr." },
      { id: 2, actor: "Chris Evans" },
      { id: 3, actor: "Mark Ruffalo" },
      { id: 4, actor: "Chris Hemsworth" },
      { id: 5, actor: "Scarlett Johansson" },
    ],
  },
  {
    poster: "/images/Movies/Posters/67_The Shining.jpg",
    id: 67,
    title: "The Shining",
    rating: 8.4,
    year: 1980,
    category: "Drama",
    related: "The Shining",
    related_id: 1,
    director: "Stanley Kubrick",
    actors: [
      { id: 1, actor: "Jack Nicholson" },
      { id: 2, actor: "Shelley Duvall" },
      { id: 3, actor: "Danny Lloyd" },
      { id: 4, actor: "Scatman Crothers" },
      { id: 5, actor: "Barry Nelson" },
    ],
  },
  {
    poster: "/images/Movies/Posters/70_Inglorious Basterds.jpg",
    id: 70,
    title: "Inglourious Basterds",
    rating: 8.3,
    year: 2009,
    category: "War",
    related: "Inglourious Basterds",
    related_id: 1,
    director: "Quentin Tarantino",
    actors: [
      { id: 1, actor: "Brad Pitt" },
      { id: 2, actor: "Christoph Waltz" },
      { id: 3, actor: "Diane Kruger" },
      { id: 4, actor: "Eli Roth" },
      { id: 5, actor: "Melanie Laurent" },
    ],
  },
  {
    poster: "/images/Movies/Posters/73_American Beauty.jpg",
    id: 73,
    title: "American Beauty",
    rating: 8.3,
    year: 1999,
    category: "Drama",
    related: "American Beauty",
    related_id: 1,
    director: "Sam Mendes",
    actors: [
      { id: 1, actor: "Kevin Spacey" },
      { id: 2, actor: "Annette Bening" },
      { id: 3, actor: "Thora Birch" },
      { id: 4, actor: "Wes Bentley" },
      { id: 5, actor: "Chris Cooper" },
    ],
  },
  {
    poster: "/images/Movies/Posters/74_Oldboy.jpg",
    id: 74,
    title: "Oldboy",
    rating: 8.4,
    year: 2003,
    category: "Mind Fuck",
    related: "Oldboy",
    related_id: 1,
    director: "Park Chan-wook",
    actors: [
      { id: 1, actor: "Choi Min-sik" },
      { id: 2, actor: "Yoo Ji-tae" },
      { id: 3, actor: "Kang Hye-jeong" },
      { id: 4, actor: "Oh Dae-su" },
      { id: 5, actor: "Kim Byeong-ok" },
    ],
  },
  {
    poster: "/images/Movies/Posters/76_Amadeus.jpg",
    id: 76,
    title: "Amadeus",
    rating: 8.3,
    year: 1984,
    category: "Music",
    related: "Amadeus",
    related_id: 1,
    director: "Milos Forman",
    actors: [
      { id: 1, actor: "Tom Hulce" },
      { id: 2, actor: "F. Murray Abraham" },
      { id: 3, actor: "Elizabeth Berridge" },
      { id: 4, actor: "Roy Dotrice" },
      { id: 5, actor: "Simon Callow" },
    ],
  },
  {
    poster: "/images/Movies/Posters/78_Das Boot.jpg",
    id: 78,
    title: "Das Boot",
    rating: 8.4,
    year: 1981,
    category: "War",
    related: "Das Boot",
    related_id: 1,
    director: "Wolfgang Petersen",
    actors: [
      { id: 1, actor: "Jürgen Prochnow" },
      { id: 2, actor: "Herbert Grönemeyer" },
      { id: 3, actor: "Klaus Wennemann" },
      { id: 4, actor: "Erwin Leder" },
      { id: 5, actor: "Hubertus Bengsch" },
    ],
  },
  {
    poster: "/images/Movies/Posters/80_Braveheart.jpg",
    id: 80,
    title: "Braveheart",
    rating: 8.4,
    year: 1995,
    category: "History",
    related: "Braveheart",
    related_id: 1,
    director: "Mel Gibson",
    actors: [
      { id: 1, actor: "Mel Gibson" },
      { id: 2, actor: "Sophie Marceau" },
      { id: 3, actor: "Patrick McGoohan" },
      { id: 4, actor: "Catherine McCormack" },
      { id: 5, actor: "David O'Hara" },
    ],
  },
  {
    poster: "/images/Movies/Posters/81_Joker.jpg",
    id: 81,
    title: "Joker",
    rating: 8.4,
    year: 2019,
    category: "Drama",
    related: "Joker",
    related_id: 1,
    director: "Todd Phillips",
    actors: [
      { id: 1, actor: "Joaquin Phoenix" },
      { id: 2, actor: "Robert De Niro" },
      { id: 3, actor: "Zazie Beetz" },
      { id: 4, actor: "Frances Conroy" },
      { id: 5, actor: "Brett Cullen" },
    ],
  },
  {
    poster: "/images/Movies/Posters/82_Princess Mononoke.jpg",
    id: 82,
    title: "Princess Mononoke",
    rating: 8.6,
    year: 1997,
    category: "Animation",
    related: "Princess Mononoke",
    related_id: 1,
    director: "Hayao Miyazaki",
    actors: [
      { id: 1, actor: "Yōji Matsuda" },
      { id: 2, actor: "Yuriko Ishida" },
      { id: 3, actor: "Bunta Sugawara" },
      { id: 4, actor: "Ghibli" },
      { id: 5, actor: "Akihiro Miwa" },
    ],
  },
  {
    poster: "/images/Movies/Posters/83_Good Will Hunting.jpg",
    id: 83,
    title: "Good Will Hunting",
    rating: 8.3,
    year: 1997,
    category: "Drama",
    related: "Good Will Hunting",
    related_id: 1,
    director: "Gus Van Sant",
    actors: [
      { id: 1, actor: "Matt Damon" },
      { id: 2, actor: "Robin Williams" },
      { id: 3, actor: "Ben Affleck" },
      { id: 4, actor: "Minnie Driver" },
      { id: 5, actor: "Stellan Skarsgård" },
    ],
  },
  {
    poster: "/images/Movies/Posters/84_Your Name.jpg",
    id: 84,
    title: "Your Name",
    rating: 8.9,
    year: 2016,
    category: "Animation",
    related: "Your Name",
    related_id: 1,
    director: "Makoto Shinkai",
    actors: [
      { id: 1, actor: "Ryo Narita" },
      { id: 2, actor: "Mone Kamishiraishi" },
      { id: 3, actor: "Kenshi Yonezu" },
      { id: 4, actor: "Sayaka Kinoshita" },
      { id: 5, actor: "Kaito Ishikawa" },
    ],
  },
  {
    poster: "/images/Movies/Posters/85_Once Upon a Time in America.jpg",
    id: 85,
    title: "Once Upon a Time in America",
    rating: 8.4,
    year: 1984,
    category: "Mafia",
    related: "Once Upon a Time in America",
    related_id: 1,
    director: "Sergio Leone",
    actors: [
      { id: 1, actor: "Robert De Niro" },
      { id: 2, actor: "James Woods" },
      { id: 3, actor: "Elizabeth McGovern" },
      { id: 4, actor: "Joe Pesci" },
      { id: 5, actor: "Burt Young" },
    ],
  },
  {
    poster: "/images/Movies/Posters/89_Capernaum.jpg",
    id: 89,
    title: "Capernaum",
    rating: 8.4,
    year: 2018,
    category: "Drama",
    related: "Capernaum",
    related_id: 1,
    director: "Nadine Labaki",
    actors: [
      { id: 1, actor: "Zain Al Rafeea" },
      { id: 2, actor: "Yordanos Shiferaw" },
      { id: 3, actor: "Kawthar Al Haddad" },
      { id: 4, actor: "Fadi Kamel" },
      { id: 5, actor: "Nadine Labaki" },
    ],
  },
  {
    poster: "/images/Movies/Posters/90_Requiem for a Dream.jpg",
    id: "90",
    title: "Requiem for a Dream",
    rating: 8.3,
    year: 2000,
    category: "Drama",
    related: "Requiem for a Dream",
    related_id: 1,
    director: "Darren Aronofsky",
    actors: [
      { id: 1, actor: "Ellen Burstyn" },
      { id: 2, actor: "Jared Leto" },
      { id: 3, actor: "Jennifer Connelly" },
      { id: 4, actor: "Marlon Wayans" },
      { id: 5, actor: "Christopher McDonald" },
    ],
  },
  {
    poster: "/images/Movies/Posters/91_Come and See.jpg",
    id: "91",
    title: "Come and See",
    rating: 8.3,
    year: 1985,
    category: "Drama",
    related: "Come and See",
    related_id: 1,
    director: "Elem Klimov",
    actors: [
      { id: 1, actor: "Aleksei Kravchenko" },
      { id: 2, actor: "Olga Mironova" },
      { id: 3, actor: "Liubomiras Laucevičius" },
      { id: 4, actor: "Viktor Mikhailov" },
      { id: 5, actor: "Aleksei Anischenko" },
    ],
  },
  {
    poster: "/images/Movies/Posters/94_Oppenheimer.jpg",
    id: "94",
    title: "Oppenheimer",
    rating: 8.3,
    year: 2023,
    category: "Drama",
    related: "Oppenheimer",
    related_id: 1,
    director: "Christopher Nolan",
    actors: [
      { id: 1, actor: "Cillian Murphy" },
      { id: 2, actor: "Emily Blunt" },
      { id: 3, actor: "Matt Damon" },
      { id: 4, actor: "Robert Downey Jr." },
      { id: 5, actor: "Florence Pugh" },
    ],
  },
  {
    poster:
      "/images/Movies/Posters/95_Eternal Sunshine of the Spotless Mind.jpg",
    id: "95",
    title: "Eternal Sunshine of the Spotless Mind",
    rating: 8.3,
    year: 2004,
    category: "Drama",
    related: "Eternal Sunshine of the Spotless Mind",
    related_id: 1,
    director: "Michel Gondry",
    actors: [
      { id: 1, actor: "Jim Carrey" },
      { id: 2, actor: "Kate Winslet" },
      { id: 3, actor: "Elijah Wood" },
      { id: 4, actor: "Mark Ruffalo" },
      { id: 5, actor: "Kirsten Dunst" },
    ],
  },
  {
    poster: "/images/Movies/Posters/96_The Hunt.jpg",
    id: "96",
    title: "The Hunt",
    rating: 8.3,
    year: 2012,
    category: "Drama",
    related: "The Hunt",
    related_id: 1,
    director: "Thomas Vinterberg",
    actors: [
      { id: 1, actor: "Mads Mikkelsen" },
      { id: 2, actor: "Thomas Bo Larsen" },
      { id: 3, actor: "Annika Wedderkopp" },
      { id: 4, actor: "Alexandria Watterson" },
      { id: 5, actor: "Lars Ranthe" },
    ],
  },
  {
    poster: "/images/Movies/Posters/97_2001 a Space Odyssey.jpg",
    id: "97",
    title: "2001: A Space Odyssey",
    rating: 8.3,
    year: 1968,
    category: "Drama",
    related: "2001: A Space Odyssey",
    related_id: 1,
    director: "Stanley Kubrick",
    actors: [
      { id: 1, actor: "Keir Dullea" },
      { id: 2, actor: "Gary Lockwood" },
      { id: 3, actor: "William Sylvester" },
      { id: 4, actor: "Douglas Rain" },
      { id: 5, actor: "Daniel Richter" },
    ],
  },
  {
    poster: "/images/Movies/Posters/98_Reservoir Dogs.jpg",
    id: "98",
    title: "Reservoir Dogs",
    rating: 8.3,
    year: 1992,
    category: "Drama",
    related: "Reservoir Dogs",
    related_id: 1,
    director: "Quentin Tarantino",
    actors: [
      { id: 1, actor: "Harvey Keitel" },
      { id: 2, actor: "Tim Roth" },
      { id: 3, actor: "Michael Madsen" },
      { id: 4, actor: "Chris Penn" },
      { id: 5, actor: "Steve Buscemi" },
    ],
  },
  {
    poster: "/images/Movies/Posters/103_Incendies.jpg",
    id: "103",
    title: "Incendies",
    rating: 8.3,
    year: 2010,
    category: "Drama",
    related: "Incendies",
    related_id: 1,
    director: "Denis Villeneuve",
    actors: [
      { id: 1, actor: "Lubna Azabal" },
      { id: 2, actor: "Mélissa Désormeaux-Poulin" },
      { id: 3, actor: "Maxim Gaudette" },
      { id: 4, actor: "Rémy Girard" },
      { id: 5, actor: "Nabil Saleh" },
    ],
  },
  {
    poster: "/images/Movies/Posters/108_Scarface.jpg",
    id: "108",
    title: "Scarface",
    rating: 8.3,
    year: 1983,
    category: "Drama",
    related: "Scarface",
    related_id: 1,
    director: "Brian De Palma",
    actors: [
      { id: 1, actor: "Al Pacino" },
      { id: 2, actor: "Michelle Pfeiffer" },
      { id: 3, actor: "Steven Bauer" },
      { id: 4, actor: "Mary Elizabeth Mastrantonio" },
      { id: 5, actor: "Robert Loggia" },
    ],
  },
  {
    poster: "/images/Movies/Posters/109_Full Metal Jacket.jpg",
    id: "109",
    title: "Full Metal Jacket",
    rating: 8.3,
    year: 1987,
    category: "Drama",
    related: "Full Metal Jacket",
    related_id: 1,
    director: "Stanley Kubrick",
    actors: [
      { id: 1, actor: "Matthew Modine" },
      { id: 2, actor: "R. Lee Ermey" },
      { id: 3, actor: "Vincent D'Onofrio" },
      { id: 4, actor: "Arliss Howard" },
      { id: 5, actor: "Lee Ermey" },
    ],
  },
  {
    poster: "/images/Movies/Posters/110_Amelie.jpg",
    id: "110",
    title: "Amélie",
    rating: 8.3,
    year: 2001,
    category: "Drama",
    related: "Amélie",
    related_id: 1,
    director: "Jean-Pierre Jeunet",
    actors: [
      { id: 1, actor: "Audrey Tautou" },
      { id: 2, actor: "Mathieu Kassovitz" },
      { id: 3, actor: "Rufus" },
      { id: 4, actor: "Lorella Cravotta" },
      { id: 5, actor: "Artus de Penguern" },
    ],
  },
  {
    poster: "/images/Movies/Posters/111_Heat.jpg",
    id: "111",
    title: "Heat",
    rating: 8.3,
    year: 1995,
    category: "Drama",
    related: "Heat",
    related_id: 1,
    director: "Michael Mann",
    actors: [
      { id: 1, actor: "Al Pacino" },
      { id: 2, actor: "Robert De Niro" },
      { id: 3, actor: "Val Kilmer" },
      { id: 4, actor: "Jon Voight" },
      { id: 5, actor: "Tom Sizemore" },
    ],
  },
  {
    poster: "/images/Movies/Posters/112_A Clockwork Orange.jpg",
    id: "112",
    title: "A Clockwork Orange",
    rating: 8.3,
    year: 1971,
    category: "Drama",
    related: "A Clockwork Orange",
    related_id: 1,
    director: "Stanley Kubrick",
    actors: [
      { id: 1, actor: "Malcolm McDowell" },
      { id: 2, actor: "Patrick Magee" },
      { id: 3, actor: "Michael Bates" },
      { id: 4, actor: "Warren Clarke" },
      { id: 5, actor: "Adrienne Corri" },
    ],
  },
  {
    poster: "/images/Movies/Posters/115_The Sting.jpg",
    id: "115",
    title: "The Sting",
    rating: 8.3,
    year: 1973,
    category: "Drama",
    related: "The Sting",
    related_id: 1,
    director: "George Roy Hill",
    actors: [
      { id: 1, actor: "Paul Newman" },
      { id: 2, actor: "Robert Redford" },
      { id: 3, actor: "Robert Shaw" },
      { id: 4, actor: "Charles Durning" },
      { id: 5, actor: "Eileen Brennan" },
    ],
  },
  {
    poster: "/images/Movies/Posters/116_A Separation.jpg",
    id: "116",
    title: "A Separation",
    rating: 8.3,
    year: 2011,
    category: "Drama",
    related: "A Separation",
    related_id: 1,
    director: "Asghar Farhadi",
    actors: [
      { id: 1, actor: "Leila Hatami" },
      { id: 2, actor: "Peyman Maadi" },
      { id: 3, actor: "Sarah Kazemy" },
      { id: 4, actor: "Shahab Hosseini" },
      { id: 5, actor: "Sareh Bayat" },
    ],
  },
  {
    poster: "/images/Movies/Posters/118.01_Die Hard.jpg",
    id: "118.01",
    title: "Die Hard",
    rating: 8.2,
    year: 1988,
    category: "Drama",
    related: "Die Hard",
    related_id: 1,
    director: "John McTiernan",
    actors: [
      { id: 1, actor: "Bruce Willis" },
      { id: 2, actor: "Alan Rickman" },
      { id: 3, actor: "Bonnie Bedelia" },
      { id: 4, actor: "Reginald VelJohnson" },
      { id: 5, actor: "Paul Gleason" },
    ],
  },
  {
    poster: "/images/Movies/Posters/118.02_Die Hard 2.jpg",
    id: "118.02",
    title: "Die Hard 2",
    rating: 7.1,
    year: 1990,
    category: "Drama",
    related: "Die Hard 2",
    related_id: 1,
    director: "Renny Harlin",
    actors: [
      { id: 1, actor: "Bruce Willis" },
      { id: 2, actor: "Bonnie Bedelia" },
      { id: 3, actor: "William Sadler" },
      { id: 4, actor: "Franco Nero" },
      { id: 5, actor: "John Amos" },
    ],
  },
  {
    poster: "/images/Movies/Posters/118.03_Die Hard with a Vengeance.jpg",
    id: "118.03",
    title: "Die Hard with a Vengeance",
    rating: 7.6,
    year: 1995,
    category: "Drama",
    related: "Die Hard with a Vengeance",
    related_id: 1,
    director: "John McTiernan",
    actors: [
      { id: 1, actor: "Bruce Willis" },
      { id: 2, actor: "Samuel L. Jackson" },
      { id: 3, actor: "Jeremy Irons" },
      { id: 4, actor: "Graham Greene" },
      { id: 5, actor: "Colleen Camp" },
    ],
  },
  {
    poster: "/images/Movies/Posters/118.04_Live Free or Die Hard.jpg",
    id: "118.04",
    title: "Live Free or Die Hard",
    rating: 7.1,
    year: 2007,
    category: "Drama",
    related: "Live Free or Die Hard",
    related_id: 1,
    director: "Len Wiseman",
    actors: [
      { id: 1, actor: "Bruce Willis" },
      { id: 2, actor: "Justin Long" },
      { id: 3, actor: "Timothy Olyphant" },
      { id: 4, actor: "Maggie Q" },
      { id: 5, actor: "Clifton Collins Jr." },
    ],
  },
  {
    poster: "/images/Movies/Posters/118.05_A Good Day to Die Hard.jpg",
    id: "118.05",
    title: "A Good Day to Die Hard",
    rating: 5.3,
    year: 2013,
    category: "Drama",
    related: "A Good Day to Die Hard",
    related_id: 1,
    director: "John Moore",
    actors: [
      { id: 1, actor: "Bruce Willis" },
      { id: 2, actor: "Jai Courtney" },
      { id: 3, actor: "Sebastian Koch" },
      { id: 4, actor: "Mary Elizabeth Winstead" },
      { id: 5, actor: "Cole Hauser" },
    ],
  },
  {
    poster: "/images/Movies/Posters/121_Snatch.jpg",
    id: "121",
    title: "Snatch",
    rating: 8.3,
    year: 2000,
    category: "Drama",
    related: "Snatch",
    related_id: 1,
    director: "Guy Ritchie",
    actors: [
      { id: 1, actor: "Jason Statham" },
      { id: 2, actor: "Brad Pitt" },
      { id: 3, actor: "Benicio Del Toro" },
      { id: 4, actor: "Dennis Farina" },
      { id: 5, actor: "Vinnie Jones" },
    ],
  },
  {
    poster: "/images/Movies/Posters/123_L.A. Confidential.jpg",
    id: "123",
    title: "L.A. Confidential",
    rating: 8.2,
    year: 1997,
    category: "Drama",
    related: "L.A. Confidential",
    related_id: 1,
    director: "Curtis Hanson",
    actors: [
      { id: 1, actor: "Russell Crowe" },
      { id: 2, actor: "Guy Pearce" },
      { id: 3, actor: "Kim Basinger" },
      { id: 4, actor: "Kevin Spacey" },
      { id: 5, actor: "Danny DeVito" },
    ],
  },
  {
    poster: "/images/Movies/Posters/124_1917.jpg",
    id: "124",
    title: "1917",
    rating: 8.3,
    year: 2019,
    category: "Drama",
    related: "1917",
    related_id: 1,
    director: "Sam Mendes",
    actors: [
      { id: 1, actor: "George MacKay" },
      { id: 2, actor: "Dean-Charles Chapman" },
      { id: 3, actor: "Mark Strong" },
      { id: 4, actor: "Andrew Scott" },
      { id: 5, actor: "Claire Duburcq" },
    ],
  },
  {
    poster: "/images/Movies/Posters/126_Taxi Driver.jpg",
    id: "126",
    title: "Taxi Driver",
    rating: 8.3,
    year: 1976,
    category: "Drama",
    related: "Taxi Driver",
    related_id: 1,
    director: "Martin Scorsese",
    actors: [
      { id: 1, actor: "Robert De Niro" },
      { id: 2, actor: "Jodie Foster" },
      { id: 3, actor: "Cybill Shepherd" },
      { id: 4, actor: "Albert Brooks" },
      { id: 5, actor: "Harvey Keitel" },
    ],
  },
  {
    poster: "/images/Movies/Posters/127_Downfall.jpg",
    id: "127",
    title: "Downfall",
    rating: 8.2,
    year: 2004,
    category: "Drama",
    related: "Downfall",
    related_id: 1,
    director: "Oliver Hirschbiegel",
    actors: [
      { id: 1, actor: "Bruno Ganz" },
      { id: 2, actor: "Alexandra Maria Lara" },
      { id: 3, actor: "Ulrich Matthes" },
      { id: 4, actor: "Juliane Köhler" },
      { id: 5, actor: "Heino Ferch" },
    ],
  },
  {
    poster: "/images/Movies/Posters/128_The Truman Show.jpg",
    id: "128",
    title: "The Truman Show",
    rating: 8.1,
    year: 1998,
    category: "Drama",
    related: "The Truman Show",
    related_id: 1,
    director: "Peter Weir",
    actors: [
      { id: 1, actor: "Jim Carrey" },
      { id: 2, actor: "Laura Linney" },
      { id: 3, actor: "Noah Emmerich" },
      { id: 4, actor: "Natascha McElhone" },
      { id: 5, actor: "Paul Giamatti" },
    ],
  },
  {
    poster: "/images/Movies/Posters/129_For a Few Dollars More.jpg",
    id: "129",
    title: "For a Few Dollars More",
    rating: 8.2,
    year: 1965,
    category: "Drama",
    related: "For a Few Dollars More",
    related_id: 1,
    director: "Sergio Leone",
    actors: [
      { id: 1, actor: "Clint Eastwood" },
      { id: 2, actor: "Lee Van Cleef" },
      { id: 3, actor: "Gian Maria Volonté" },
      { id: 4, actor: "Mario Brega" },
      { id: 5, actor: "Klaus Kinski" },
    ],
  },
  {
    poster: "/images/Movies/Posters/131_The Wolf of Wall Street.jpg",
    id: "131",
    title: "The Wolf of Wall Street",
    rating: 8.2,
    year: 2013,
    category: "Drama",
    related: "The Wolf of Wall Street",
    related_id: 1,
    director: "Martin Scorsese",
    actors: [
      { id: 1, actor: "Leonardo DiCaprio" },
      { id: 2, actor: "Jonah Hill" },
      { id: 3, actor: "Margot Robbie" },
      { id: 4, actor: "Matthew McConaughey" },
      { id: 5, actor: "Rob Reiner" },
    ],
  },
  {
    poster: "/images/Movies/Posters/133_Green Book.jpg",
    id: "133",
    title: "Green Book",
    rating: 8.2,
    year: 2018,
    category: "Drama",
    related: "Green Book",
    related_id: 1,
    director: "Peter Farrelly",
    actors: [
      { id: 1, actor: "Viggo Mortensen" },
      { id: 2, actor: "Mahershala Ali" },
      { id: 3, actor: "Linda Cardellini" },
      { id: 4, actor: "Sebastian Maniscalco" },
      { id: 5, actor: "Dimiter D. Marinov" },
    ],
  },
  {
    poster: "/images/Movies/Posters/135_The Father.jpg",
    id: "135",
    title: "The Father",
    rating: 8.3,
    year: 2020,
    category: "Drama",
    related: "The Father",
    related_id: 1,
    director: "Florian Zeller",
    actors: [
      { id: 1, actor: "Anthony Hopkins" },
      { id: 2, actor: "Olivia Colman" },
      { id: 3, actor: "Mark Gatiss" },
      { id: 4, actor: "Imogen Poots" },
      { id: 5, actor: "Rufus Sewell" },
    ],
  },
  {
    poster: "/images/Movies/Posters/139.01_Top Gun.jpg",
    id: "139.01",
    title: "Top Gun",
    rating: 6.9,
    year: 1986,
    category: "Drama",
    related: "Top Gun",
    related_id: 1,
    director: "Tony Scott",
    actors: [
      { id: 1, actor: "Tom Cruise" },
      { id: 2, actor: "Kelly McGillis" },
      { id: 3, actor: "Val Kilmer" },
      { id: 4, actor: "Anthony Edwards" },
      { id: 5, actor: "Tom Skerritt" },
    ],
  },
  {
    poster: "/images/Movies/Posters/139.02_Top Gun Maverick.jpg",
    id: "139.02",
    title: "Top Gun Maverick",
    rating: 7.7,
    year: 2022,
    category: "Drama",
    related: "Top Gun Maverick",
    related_id: 1,
    director: "Joseph Kosinski",
    actors: [
      { id: 1, actor: "Tom Cruise" },
      { id: 2, actor: "Miles Teller" },
      { id: 3, actor: "Jennifer Connelly" },
      { id: 4, actor: "Jon Hamm" },
      { id: 5, actor: "Bashir Salahuddin" },
    ],
  },
  {
    poster: "/images/Movies/Posters/140_Shutter Island.jpg",
    id: "140",
    title: "Shutter Island",
    rating: 8.2,
    year: 2010,
    category: "Drama",
    related: "Shutter Island",
    related_id: 1,
    director: "Martin Scorsese",
    actors: [
      { id: 1, actor: "Leonardo DiCaprio" },
      { id: 2, actor: "Mark Ruffalo" },
      { id: 3, actor: "Ben Kingsley" },
      { id: 4, actor: "Michelle Williams" },
      { id: 5, actor: "Emily Mortimer" },
    ],
  },
  {
    poster: "/images/Movies/Posters/141_There Will be Blood.jpg",
    id: "141",
    title: "There Will Be Blood",
    rating: 8.2,
    year: 2007,
    category: "Drama",
    related: "There Will Be Blood",
    related_id: 1,
    director: "Paul Thomas Anderson",
    actors: [
      { id: 1, actor: "Daniel Day-Lewis" },
      { id: 2, actor: "Paul Dano" },
      { id: 3, actor: "Ciarán Hinds" },
      { id: 4, actor: "Kevin J. O'Connor" },
      { id: 5, actor: "Dillon Freasier" },
    ],
  },
  {
    poster: "/images/Movies/Posters/142_Casino.jpg",
    id: "142",
    title: "Casino",
    rating: 8.2,
    year: 1995,
    category: "Drama",
    related: "Casino",
    related_id: 1,
    director: "Martin Scorsese",
    actors: [
      { id: 1, actor: "Robert De Niro" },
      { id: 2, actor: "Sharon Stone" },
      { id: 3, actor: "Joe Pesci" },
      { id: 4, actor: "James Woods" },
      { id: 5, actor: "Don Rickles" },
    ],
  },
  {
    poster: "/images/Movies/Posters/143.01_Jurassic Park.jpg",
    id: "143.01",
    title: "Jurassic Park",
    rating: 8.1,
    year: 1993,
    category: "Drama",
    related: "Jurassic Park",
    related_id: 1,
    director: "Steven Spielberg",
    actors: [
      { id: 1, actor: "Sam Neill" },
      { id: 2, actor: "Laura Dern" },
      { id: 3, actor: "Jeff Goldblum" },
      { id: 4, actor: "Richard Attenborough" },
      { id: 5, actor: "Bob Peck" },
    ],
  },
  {
    poster: "/images/Movies/Posters/143.02_Jurassic Park_The Lost World.jpg",
    id: "143.02",
    title: "The Lost World: Jurassic Park",
    rating: 6.6,
    year: 1997,
    category: "Drama",
    related: "The Lost World: Jurassic Park",
    related_id: 1,
    director: "Steven Spielberg",
    actors: [
      { id: 1, actor: "Jeff Goldblum" },
      { id: 2, actor: "Julianne Moore" },
      { id: 3, actor: "Pete Postlethwaite" },
      { id: 4, actor: "Arliss Howard" },
      { id: 5, actor: "Richard Attenborough" },
    ],
  },
  {
    poster: "/images/Movies/Posters/143.03_Jurassic Park 3.jpg",
    id: "143.03",
    title: "Jurassic Park III",
    rating: 5.9,
    year: 2001,
    category: "Drama",
    related: "Jurassic Park III",
    related_id: 1,
    director: "Joe Johnston",
    actors: [
      { id: 1, actor: "Sam Neill" },
      { id: 2, actor: "William H. Macy" },
      { id: 3, actor: "Tea Leoni" },
      { id: 4, actor: "Alessandro Nivola" },
      { id: 5, actor: "Michael Jeter" },
    ],
  },
  {
    poster: "/images/Movies/Posters/143.04_Jurassic World.jpg",
    id: "143.04",
    title: "Jurassic World",
    rating: 7.0,
    year: 2015,
    category: "Drama",
    related: "Jurassic World",
    related_id: 1,
    director: "Colin Trevorrow",
    actors: [
      { id: 1, actor: "Chris Pratt" },
      { id: 2, actor: "Bryce Dallas Howard" },
      { id: 3, actor: "Irrfan Khan" },
      { id: 4, actor: "Vincent D'Onofrio" },
      { id: 5, actor: "Omar Sy" },
    ],
  },
  {
    poster: "/images/Movies/Posters/143.05_Jurassic World Fallen Kingdom.jpg",
    id: "143.05",
    title: "Jurassic World: Fallen Kingdom",
    rating: 6.2,
    year: 2018,
    category: "Drama",
    related: "Jurassic World: Fallen Kingdom",
    related_id: 1,
    director: "J.A. Bayona",
    actors: [
      { id: 1, actor: "Chris Pratt" },
      { id: 2, actor: "Bryce Dallas Howard" },
      { id: 3, actor: "Rafe Spall" },
      { id: 4, actor: "Justice Smith" },
      { id: 5, actor: "Daniella Pineda" },
    ],
  },
  {
    poster: "/images/Movies/Posters/143.06_Jurassic World Dominion.jpg",
    id: "143.06",
    title: "Jurassic World Dominion",
    rating: 5.7,
    year: 2022,
    category: "Drama",
    related: "Jurassic World Dominion",
    related_id: 1,
    director: "Colin Trevorrow",
    actors: [
      { id: 1, actor: "Chris Pratt" },
      { id: 2, actor: "Bryce Dallas Howard" },
      { id: 3, actor: "Laura Dern" },
      { id: 4, actor: "Jeff Goldblum" },
      { id: 5, actor: "Sam Neill" },
    ],
  },
  {
    poster: "/images/Movies/Posters/145_The Sixth Sense.jpg",
    id: "145",
    title: "The Sixth Sense",
    rating: 8.1,
    year: 1999,
    category: "Drama",
    related: "The Sixth Sense",
    related_id: 1,
    director: "M. Night Shyamalan",
    actors: [
      { id: 1, actor: "Bruce Willis" },
      { id: 2, actor: "Haley Joel Osment" },
      { id: 3, actor: "Toni Collette" },
      { id: 4, actor: "Olivia Williams" },
      { id: 5, actor: "Donald Southerland" },
    ],
  },
  {
    poster: "/images/Movies/Posters/146_Pan's Labyrinth.jpg",
    id: "146",
    title: "Pan's Labyrinth",
    rating: 8.2,
    year: 2006,
    category: "Drama",
    related: "Pan's Labyrinth",
    related_id: 1,
    director: "Guillermo del Toro",
    actors: [
      { id: 1, actor: "Ivana Baquero" },
      { id: 2, actor: "Sergi López" },
      { id: 3, actor: "Maribel Verdú" },
      { id: 4, actor: "Doug Jones" },
      { id: 5, actor: "Álex Angulo" },
    ],
  },
  {
    poster: "/images/Movies/Posters/147_Unforgiven.jpg",
    id: "147",
    title: "Unforgiven",
    rating: 8.2,
    year: 1992,
    category: "Drama",
    related: "Unforgiven",
    related_id: 1,
    director: "Clint Eastwood",
    actors: [
      { id: 1, actor: "Clint Eastwood" },
      { id: 2, actor: "Gene Hackman" },
      { id: 3, actor: "Morgan Freeman" },
      { id: 4, actor: "Richard Harris" },
      { id: 5, actor: "Saul Rubinek" },
    ],
  },
  {
    poster: "/images/Movies/Posters/148_No Country for Old Men.jpg",
    id: "148",
    title: "No Country for Old Men",
    rating: 8.1,
    year: 2007,
    category: "Drama",
    related: "No Country for Old Men",
    related_id: 1,
    director: "Joel and Ethan Coen",
    actors: [
      { id: 1, actor: "Tommy Lee Jones" },
      { id: 2, actor: "Javier Bardem" },
      { id: 3, actor: "Josh Brolin" },
      { id: 4, actor: "Kelly Macdonald" },
      { id: 5, actor: "Woody Harrelson" },
    ],
  },
  {
    poster: "/images/Movies/Posters/149_A Beautiful Mind.jpg",
    id: "149",
    title: "A Beautiful Mind",
    rating: 8.2,
    year: 2001,
    category: "Drama",
    related: "A Beautiful Mind",
    related_id: 1,
    director: "Ron Howard",
    actors: [
      { id: 1, actor: "Russell Crowe" },
      { id: 2, actor: "Jennifer Connelly" },
      { id: 3, actor: "Ed Harris" },
      { id: 4, actor: "Christopher Plummer" },
      { id: 5, actor: "Adam Goldberg" },
    ],
  },
  {
    poster: "/images/Movies/Posters/150_The Thing.jpg",
    id: "150",
    title: "The Thing",
    rating: 8.1,
    year: 1982,
    category: "Drama",
    related: "The Thing",
    related_id: 1,
    director: "John Carpenter",
    actors: [
      { id: 1, actor: "Kurt Russell" },
      { id: 2, actor: "Wilford Brimley" },
      { id: 3, actor: "Keith David" },
      { id: 4, actor: "Richard Dysart" },
      { id: 5, actor: "Donald Moffat" },
    ],
  },
  {
    poster:
      "/images/Movies/Posters/180.01_Harry Potter - And the Sorcerers Stone.jpg",
    id: "180.01",
    title: "Harry Potter and the Sorcerer's Stone",
    rating: 7.6,
    year: 2001,
    category: "Drama",
    related: "Harry Potter and the Sorcerer's Stone",
    related_id: 1,
    director: "Chris Columbus",
    actors: [
      { id: 1, actor: "Daniel Radcliffe" },
      { id: 2, actor: "Emma Watson" },
      { id: 3, actor: "Rupert Grint" },
      { id: 4, actor: "Richard Harris" },
      { id: 5, actor: "Maggie Smith" },
    ],
  },
  {
    poster:
      "/images/Movies/Posters/180.02_Harry Potter - And the Chamber of Secrets.jpg",
    id: "180.02",
    title: "Harry Potter and the Chamber of Secrets",
    rating: 7.4,
    year: 2002,
    category: "Drama",
    related: "Harry Potter and the Chamber of Secrets",
    related_id: 1,
    director: "Chris Columbus",
    actors: [
      { id: 1, actor: "Daniel Radcliffe" },
      { id: 2, actor: "Emma Watson" },
      { id: 3, actor: "Rupert Grint" },
      { id: 4, actor: "Kenneth Branagh" },
      { id: 5, actor: "Ginevra de' Medici" },
    ],
  },
  {
    poster:
      "/images/Movies/Posters/180.03_Harry Potter - And the Prisoner of Azkaban.jpg",
    id: "180.03",
    title: "Harry Potter and the Prisoner of Azkaban",
    rating: 7.8,
    year: 2004,
    category: "Drama",
    related: "Harry Potter and the Prisoner of Azkaban",
    related_id: 1,
    director: "Alfonso Cuarón",
    actors: [
      { id: 1, actor: "Daniel Radcliffe" },
      { id: 2, actor: "Emma Watson" },
      { id: 3, actor: "Rupert Grint" },
      { id: 4, actor: "Gary Oldman" },
      { id: 5, actor: "David Thewlis" },
    ],
  },
  {
    poster:
      "/images/Movies/Posters/180.04_Harry Potter - And the Goblet of Fire.jpg",
    id: "180.04",
    title: "Harry Potter and the Goblet of Fire",
    rating: 7.7,
    year: 2005,
    category: "Drama",
    related: "Harry Potter and the Goblet of Fire",
    related_id: 1,
    director: "Mike Newell",
    actors: [
      { id: 1, actor: "Daniel Radcliffe" },
      { id: 2, actor: "Emma Watson" },
      { id: 3, actor: "Rupert Grint" },
      { id: 4, actor: "Ralph Fiennes" },
      { id: 5, actor: "Brendan Gleeson" },
    ],
  },
  {
    poster:
      "/images/Movies/Posters/180.05_Harry Potter - And the Order of the Phoenix.jpg",
    id: "180.05",
    title: "Harry Potter and the Order of the Phoenix",
    rating: 7.5,
    year: 2007,
    category: "Drama",
    related: "Harry Potter and the Order of the Phoenix",
    related_id: 1,
    director: "David Yates",
    actors: [
      { id: 1, actor: "Daniel Radcliffe" },
      { id: 2, actor: "Emma Watson" },
      { id: 3, actor: "Rupert Grint" },
      { id: 4, actor: "Imelda Staunton" },
      { id: 5, actor: "Helena Bonham Carter" },
    ],
  },
  {
    poster:
      "/images/Movies/Posters/180.06_Harry Potter - And the Half Blood Prince.jpg",
    id: "180.06",
    title: "Harry Potter and the Half-Blood Prince",
    rating: 7.7,
    year: 2009,
    category: "Drama",
    related: "Harry Potter and the Half-Blood Prince",
    related_id: 1,
    director: "David Yates",
    actors: [
      { id: 1, actor: "Daniel Radcliffe" },
      { id: 2, actor: "Emma Watson" },
      { id: 3, actor: "Rupert Grint" },
      { id: 4, actor: "Jim Broadbent" },
      { id: 5, actor: "Tom Felton" },
    ],
  },
  {
    poster:
      "/images/Movies/Posters/180.07_Harry Potter - And the Deathly Hallows Part 1.jpg",
    id: "180.07",
    title: "Harry Potter and the Deathly Hallows: Part 1",
    rating: 7.7,
    year: 2010,
    category: "Drama",
    related: "Harry Potter and the Deathly Hallows: Part 1",
    related_id: 1,
    director: "David Yates",
    actors: [
      { id: 1, actor: "Daniel Radcliffe" },
      { id: 2, actor: "Emma Watson" },
      { id: 3, actor: "Rupert Grint" },
      { id: 4, actor: "Ralph Fiennes" },
      { id: 5, actor: "Helena Bonham Carter" },
    ],
  },
  {
    poster:
      "/images/Movies/Posters/180.08_Harry Potter - And the Deathly Hallows Part 2.jpg",
    id: "180.08",
    title: "Harry Potter and the Deathly Hallows: Part 2",
    rating: 8.1,
    year: 2011,
    category: "Drama",
    related: "Harry Potter and the Deathly Hallows: Part 2",
    related_id: 1,
    director: "David Yates",
    actors: [
      { id: 1, actor: "Daniel Radcliffe" },
      { id: 2, actor: "Emma Watson" },
      { id: 3, actor: "Rupert Grint" },
      { id: 4, actor: "Ralph Fiennes" },
      { id: 5, actor: "Alan Rickman" },
    ],
  },
  {
    poster: "/images/Movies/Posters/251.01_Iron Man.jpg",
    id: "251.01",
    title: "Iron Man",
    rating: 7.9,
    year: 2008,
    category: "Drama",
    related: "Iron Man",
    related_id: 1,
    director: "Jon Favreau",
    actors: [
      { id: 1, actor: "Robert Downey Jr." },
      { id: 2, actor: "Gwyneth Paltrow" },
      { id: 3, actor: "Terrence Howard" },
      { id: 4, actor: "Jeff Bridges" },
      { id: 5, actor: "Leslie Bibb" },
    ],
  },
  {
    poster: "/images/Movies/Posters/251.02_Iron Man 2.jpg",
    id: "251.02",
    title: "Iron Man 2",
    rating: 7.0,
    year: 2010,
    category: "Drama",
    related: "Iron Man 2",
    related_id: 1,
    director: "Jon Favreau",
    actors: [
      { id: 1, actor: "Robert Downey Jr." },
      { id: 2, actor: "Gwyneth Paltrow" },
      { id: 3, actor: "Don Cheadle" },
      { id: 4, actor: "Scarlett Johansson" },
      { id: 5, actor: "Mickey Rourke" },
    ],
  },
  {
    poster: "/images/Movies/Posters/251.03_Iron Man 3.jpg",
    id: "251.03",
    title: "Iron Man 3",
    rating: 7.2,
    year: 2013,
    category: "Drama",
    related: "Iron Man 3",
    related_id: 1,
    director: "Shane Black",
    actors: [
      { id: 1, actor: "Robert Downey Jr." },
      { id: 2, actor: "Gwyneth Paltrow" },
      { id: 3, actor: "Ben Kingsley" },
      { id: 4, actor: "Guy Pearce" },
      { id: 5, actor: "Don Cheadle" },
    ],
  },
  {
    poster:
      "/images/Movies/Posters/252.01_Captain America The First Avenger.jpg",
    id: "252.01",
    title: "Captain America: The First Avenger",
    rating: 6.9,
    year: 2011,
    category: "Drama",
    related: "Captain America: The First Avenger",
    related_id: 1,
    director: "Joe Johnston",
    actors: [
      { id: 1, actor: "Chris Evans" },
      { id: 2, actor: "Hayley Atwell" },
      { id: 3, actor: "Sebastian Stan" },
      { id: 4, actor: "Hugo Weaving" },
      { id: 5, actor: "Tommy Lee Jones" },
    ],
  },
  {
    poster:
      "/images/Movies/Posters/252.02_Captain America The Winter Soldier.jpg",
    id: "252.02",
    title: "Captain America: The Winter Soldier",
    rating: 7.7,
    year: 2014,
    category: "Drama",
    related: "Captain America: The Winter Soldier",
    related_id: 1,
    director: "Anthony Russo, Joe Russo",
    actors: [
      { id: 1, actor: "Chris Evans" },
      { id: 2, actor: "Scarlett Johansson" },
      { id: 3, actor: "Sebastian Stan" },
      { id: 4, actor: "Anthony Mackie" },
      { id: 5, actor: "Robert Redford" },
    ],
  },
  {
    poster: "/images/Movies/Posters/252.03_Captain America Civil War.jpg",
    id: "252.03",
    title: "Captain America: Civil War",
    rating: 7.8,
    year: 2016,
    category: "Drama",
    related: "Captain America: Civil War",
    related_id: 1,
    director: "Anthony Russo, Joe Russo",
    actors: [
      { id: 1, actor: "Chris Evans" },
      { id: 2, actor: "Robert Downey Jr." },
      { id: 3, actor: "Scarlett Johansson" },
      { id: 4, actor: "Sebastian Stan" },
      { id: 5, actor: "Anthony Mackie" },
    ],
  },
  {
    poster: "/images/Movies/Posters/253.01_Thor.jpg",
    id: "253.01",
    title: "Thor",
    rating: 7.0,
    year: 2011,
    category: "Drama",
    related: "Thor",
    related_id: 1,
    director: "Kenneth Branagh",
    actors: [
      { id: 1, actor: "Chris Hemsworth" },
      { id: 2, actor: "Natalie Portman" },
      { id: 3, actor: "Tom Hiddleston" },
      { id: 4, actor: "Anthony Hopkins" },
      { id: 5, actor: "Stellan Skarsgård" },
    ],
  },
  {
    poster: "/images/Movies/Posters/253.02_Thor The Dark World.jpg",
    id: "253.02",
    title: "Thor: The Dark World",
    rating: 6.9,
    year: 2013,
    category: "Drama",
    related: "Thor: The Dark World",
    related_id: 1,
    director: "Alan Taylor",
    actors: [
      { id: 1, actor: "Chris Hemsworth" },
      { id: 2, actor: "Natalie Portman" },
      { id: 3, actor: "Tom Hiddleston" },
      { id: 4, actor: "Christopher Eccleston" },
      { id: 5, actor: "Stellan Skarsgård" },
    ],
  },
  {
    poster: "/images/Movies/Posters/253.03_Thor Ragnarok.jpg",
    id: "253.03",
    title: "Thor: Ragnarok",
    rating: 7.9,
    year: 2017,
    category: "Drama",
    related: "Thor: Ragnarok",
    related_id: 1,
    director: "Taika Waititi",
    actors: [
      { id: 1, actor: "Chris Hemsworth" },
      { id: 2, actor: "Tom Hiddleston" },
      { id: 3, actor: "Cate Blanchett" },
      { id: 4, actor: "Tessa Thompson" },
      { id: 5, actor: "Jeff Goldblum" },
    ],
  },
  {
    poster: "/images/Movies/Posters/253.04_Thor Love and Thunder.jpg",
    id: "253.04",
    title: "Thor: Love and Thunder",
    rating: 6.7,
    year: 2022,
    category: "Drama",
    related: "Thor: Love and Thunder",
    related_id: 1,
    director: "Taika Waititi",
    actors: [
      { id: 1, actor: "Chris Hemsworth" },
      { id: 2, actor: "Natalie Portman" },
      { id: 3, actor: "Tessa Thompson" },
      { id: 4, actor: "Christian Bale" },
      { id: 5, actor: "Russell Crowe" },
    ],
  },
  {
    poster: "/images/Movies/Posters/254.01_Spider Man Homecoming.jpg",
    id: "254.01",
    title: "Spider-Man: Homecoming",
    rating: 7.4,
    year: 2017,
    category: "Drama",
    related: "Spider-Man: Homecoming",
    related_id: 1,
    director: "Jon Watts",
    actors: [
      { id: 1, actor: "Tom Holland" },
      { id: 2, actor: "Michael Keaton" },
      { id: 3, actor: "Zendaya" },
      { id: 4, actor: "Jon Favreau" },
      { id: 5, actor: "Marisa Tomei" },
    ],
  },
  {
    poster: "/images/Movies/Posters/254.02_Spider Man Far from Home.jpg",
    id: "254.02",
    title: "Spider-Man: Far From Home",
    rating: 7.5,
    year: 2019,
    category: "Drama",
    related: "Spider-Man: Far From Home",
    related_id: 1,
    director: "Jon Watts",
    actors: [
      { id: 1, actor: "Tom Holland" },
      { id: 2, actor: "Samuel L. Jackson" },
      { id: 3, actor: "Zendaya" },
      { id: 4, actor: "Jake Gyllenhaal" },
      { id: 5, actor: "Jon Favreau" },
    ],
  },
  {
    poster: "/images/Movies/Posters/254.03_Spider Man No Way Home.jpg",
    id: "254.03",
    title: "Spider-Man: No Way Home",
    rating: 8.0,
    year: 2021,
    category: "Drama",
    related: "Spider-Man: No Way Home",
    related_id: 1,
    director: "Jon Watts",
    actors: [
      { id: 1, actor: "Tom Holland" },
      { id: 2, actor: "Zendaya" },
      { id: 3, actor: "Benedict Cumberbatch" },
      { id: 4, actor: "Jacob Batalon" },
      { id: 5, actor: "Alfred Molina" },
    ],
  },
  {
    poster: "/images/Movies/Posters/255.01_The Incredible Hulk.jpg",
    id: "255.01",
    title: "The Incredible Hulk",
    rating: 6.7,
    year: 2008,
    category: "Drama",
    related: "The Incredible Hulk",
    related_id: 1,
    director: "Louis Leterrier",
    actors: [
      { id: 1, actor: "Edward Norton" },
      { id: 2, actor: "Liv Tyler" },
      { id: 3, actor: "Tim Roth" },
      { id: 4, actor: "William Hurt" },
      { id: 5, actor: "Ty Burrell" },
    ],
  },
  {
    poster: "/images/Movies/Posters/256.01_Guardians of the Galaxy.jpg",
    id: "256.01",
    title: "Guardians of the Galaxy",
    rating: 8.0,
    year: 2014,
    category: "Drama",
    related: "Guardians of the Galaxy",
    related_id: 1,
    director: "James Gunn",
    actors: [
      { id: 1, actor: "Chris Pratt" },
      { id: 2, actor: "Zoe Saldana" },
      { id: 3, actor: "Dave Bautista" },
      { id: 4, actor: "Vin Diesel" },
      { id: 5, actor: "Bradley Cooper" },
    ],
  },
  {
    poster: "/images/Movies/Posters/256.02_Guardians of the Galaxy Vol 2.jpg",
    id: "256.02",
    title: "Guardians of the Galaxy Vol 2",
    rating: 7.9,
    year: 2017,
    category: "Drama",
    related: "Guardians of the Galaxy Vol 2",
    related_id: 1,
    director: "James Gunn",
    actors: [
      { id: 1, actor: "Chris Pratt" },
      { id: 2, actor: "Zoe Saldana" },
      { id: 3, actor: "Dave Bautista" },
      { id: 4, actor: "Vin Diesel" },
      { id: 5, actor: "Bradley Cooper" },
    ],
  },
  {
    poster: "/images/Movies/Posters/256.03_Guardians of the Galaxy Vol 3.jpg",
    id: "256.03",
    title: "Guardians of the Galaxy Vol 3",
    rating: 7.9,
    year: 2023,
    category: "Drama",
    related: "Guardians of the Galaxy Vol 3",
    related_id: 1,
    director: "James Gunn",
    actors: [
      { id: 1, actor: "Chris Pratt" },
      { id: 2, actor: "Zoe Saldana" },
      { id: 3, actor: "Dave Bautista" },
      { id: 4, actor: "Vin Diesel" },
      { id: 5, actor: "Bradley Cooper" },
    ],
  },
  {
    poster: "/images/Movies/Posters/257.01_Dr Strange.jpg",
    id: "257.01",
    title: "Doctor Strange",
    rating: 7.5,
    year: 2016,
    category: "Drama",
    related: "Doctor Strange",
    related_id: 1,
    director: "Scott Derrickson",
    actors: [
      { id: 1, actor: "Benedict Cumberbatch" },
      { id: 2, actor: "Chiwetel Ejiofor" },
      { id: 3, actor: "Rachel McAdams" },
      { id: 4, actor: "Benedict Wong" },
      { id: 5, actor: "Mads Mikkelsen" },
    ],
  },
  {
    poster:
      "/images/Movies/Posters/257.02_Dr Strange in the Multiverse of Madness.jpg",
    id: "257.02",
    title: "Doctor Strange in the Multiverse of Madness",
    rating: 6.9,
    year: 2022,
    category: "Drama",
    related: "Doctor Strange in the Multiverse of Madness",
    related_id: 1,
    director: "Sam Raimi",
    actors: [
      { id: 1, actor: "Benedict Cumberbatch" },
      { id: 2, actor: "Elizabeth Olsen" },
      { id: 3, actor: "Xochitl Gomez" },
      { id: 4, actor: "Rachel McAdams" },
      { id: 5, actor: "Chiwetel Ejiofor" },
    ],
  },
  {
    poster: "/images/Movies/Posters/258.01_Ant-man.jpg",
    id: "258",
    title: "Ant-man",
    rating: 7.3,
    year: 2015,
    category: "Action-Adventure",
    related: "Ant-man",
    related_id: 1,
    director: "Peyton Reed",
    actors: [
      { id: 1, actor: "Paul Rudd" },
      { id: 2, actor: "Evangeline Lilly" },
      { id: 3, actor: "Michael Douglas" },
      { id: 4, actor: "Corey Stoll" },
      { id: 5, actor: "Bobby Cannavale" },
    ],
  },
  {
    poster: "/images/Movies/Posters/258.02_Ant-man and the Wasp.jpg",
    id: "258.02",
    title: "Ant-man and the Wasp",
    rating: 7.1,
    year: 2018,
    category: "Action-Adventure",
    related: "Ant-man and the Wasp",
    related_id: 1,
    director: "Peyton Reed",
    actors: [
      { id: 1, actor: "Paul Rudd" },
      { id: 2, actor: "Evangeline Lilly" },
      { id: 3, actor: "Michael Douglas" },
      { id: 4, actor: "Hannah John-Kamen" },
      { id: 5, actor: "Michael Peña" },
    ],
  },
  {
    poster: "/images/Movies/Posters/258.03_Ant-man Quantumania.jpg",
    id: "258.03",
    title: "Ant-man Quantumania",
    rating: 6.5,
    year: 2023,
    category: "Action-Adventure",
    related: "Ant-man Quantumania",
    related_id: 1,
    director: "Peyton Reed",
    actors: [
      { id: 1, actor: "Paul Rudd" },
      { id: 2, actor: "Evangeline Lilly" },
      { id: 3, actor: "Jonathan Majors" },
      { id: 4, actor: "Kathryn Newton" },
      { id: 5, actor: "Michelle Pfeiffer" },
    ],
  },
  {
    poster: "/images/Movies/Posters/259.01_Black Panther.jpg",
    id: "259.01",
    title: "Black Panther",
    rating: 7.3,
    year: 2018,
    category: "Action-Adventure",
    related: "Black Panther",
    related_id: 1,
    director: "Ryan Coogler",
    actors: [
      { id: 1, actor: "Chadwick Boseman" },
      { id: 2, actor: "Michael B. Jordan" },
      { id: 3, actor: "Lupita Nyong'o" },
      { id: 4, actor: "Danai Gurira" },
      { id: 5, actor: "Martin Freeman" },
    ],
  },
  {
    poster: "/images/Movies/Posters/259.02_Black Panther Wakanda Forever.jpg",
    id: "259.02",
    title: "Black Panther Wakanda Forever",
    rating: 6.8,
    year: 2022,
    category: "Action-Adventure",
    related: "Black Panther Wakanda Forever",
    related_id: 1,
    director: "Ryan Coogler",
    actors: [
      { id: 1, actor: "Letitia Wright" },
      { id: 2, actor: "Angela Bassett" },
      { id: 3, actor: "Lupita Nyong'o" },
      { id: 4, actor: "Winston Duke" },
      { id: 5, actor: "Tenoch Huerta" },
    ],
  },
  {
    poster: "/images/Movies/Posters/260.01_Captain Marvel.jpg",
    id: "260.01",
    title: "Captain Marvel",
    rating: 6.8,
    year: 2019,
    category: "Action-Adventure",
    related: "Captain Marvel",
    related_id: 1,
    director: "Anna Boden, Ryan Fleck",
    actors: [
      { id: 1, actor: "Brie Larson" },
      { id: 2, actor: "Samuel L. Jackson" },
      { id: 3, actor: "Ben Mendelsohn" },
      { id: 4, actor: "Jude Law" },
      { id: 5, actor: "Lashana Lynch" },
    ],
  },
  {
    poster: "/images/Movies/Posters/260.02_The Marvels.jpg",
    id: "260.02",
    title: "The Marvels",
    rating: 6.9,
    year: 2023,
    category: "Action-Adventure",
    related: "The Marvels",
    related_id: 1,
    director: "Nia DaCosta",
    actors: [
      { id: 1, actor: "Brie Larson" },
      { id: 2, actor: "Iman Vellani" },
      { id: 3, actor: "Teyonah Parris" },
      { id: 4, actor: "Park Seo-jun" },
      { id: 5, actor: "Zawe Ashton" },
    ],
  },
  {
    poster: "/images/Movies/Posters/261_Black Widow.jpg",
    id: "261",
    title: "Black Widow",
    rating: 6.7,
    year: 2021,
    category: "Action-Adventure",
    related: "Black Widow",
    related_id: 1,
    director: "Cate Shortland",
    actors: [
      { id: 1, actor: "Scarlett Johansson" },
      { id: 2, actor: "Florence Pugh" },
      { id: 3, actor: "David Harbour" },
      { id: 4, actor: "Rachel Weisz" },
      { id: 5, actor: "OT Fagbenie" },
    ],
  },
  {
    poster:
      "/images/Movies/Posters/262.01_Shang-Chi and the Legend of the Ten Rings.jpg",
    id: "262.01",
    title: "Shang-Chi and the Legend of the Ten Rings",
    rating: 7.5,
    year: 2021,
    category: "Action-Adventure",
    related: "Shang-Chi and the Legend of the Ten Rings",
    related_id: 1,
    director: "Destin Daniel Cretton",
    actors: [
      { id: 1, actor: "Simu Liu" },
      { id: 2, actor: "Awkwafina" },
      { id: 3, actor: "Meng'er Zhang" },
      { id: 4, actor: "Fala Chen" },
      { id: 5, actor: "Tony Leung" },
    ],
  },
  {
    poster: "/images/Movies/Posters/263.01_Eternals.jpg",
    id: "263.01",
    title: "Eternals",
    rating: 6.3,
    year: 2021,
    category: "Action-Adventure",
    related: "Eternals",
    related_id: 1,
    director: "Chloé Zhao",
    actors: [
      { id: 1, actor: "Gemma Chan" },
      { id: 2, actor: "Richard Madden" },
      { id: 3, actor: "Angelina Jolie" },
      { id: 4, actor: "Kumail Nanjiani" },
      { id: 5, actor: "Brian Tyree Henry" },
    ],
  },
];
