export const movies = [
  {
    id: 1,
    title: "Fight Club 1",
    year: 1999,
    rating: 8.3,
    category: "mind fuck",
    related: "fight_club",
    related_id: "1",
    director: "David Fincher",
    actors: [
      { id: 1, actor: "Brad Pitt" },
      { id: 2, actor: "Edward Norton" },
      { id: 3, actor: "Martha1" },
      { id: 4, actor: "Martha2" },
      { id: 5, actor: "Martha3" },
    ],
    poster: "/images/Movies/Posters/11_Fight Club.jpg",
  },
  {
    id: 2,
    title: "Fight Club 2",
    year: 1999,
    rating: 8.3,
    category: "mind fuck",
    related: "fight_club",
    related_id: "2",
    director: "David Fincher",
    actors: [
      { id: 1, actor: "Brad Pitt" },
      { id: 2, actor: "Edward Norton" },
      { id: 3, actor: "Martha1" },
      { id: 4, actor: "Martha2" },
      { id: 5, actor: "Martha3" },
    ],
    poster: "/images/Movies/Posters/11_Fight Club.jpg",
  },
  {
    id: 3,
    title: "Fight Club 3",
    year: 1999,
    rating: 8.3,
    category: "mind fuck",
    related: "",
    related_id: "3",
    director: "David Fincher",
    actors: [
      { id: 1, actor: "Brad Pitt" },
      { id: 2, actor: "Edward Norton" },
      { id: 3, actor: "Martha1" },
      { id: 4, actor: "Martha2" },
      { id: 5, actor: "Martha3" },
    ],
    poster: "/images/Movies/Posters/11_Fight Club.jpg",
  },
  {
    id: 4,
    title: "Fight Club 3",
    year: 1999,
    rating: 8.3,
    category: "mind fuck",
    related: "",
    related_id: "3",
    director: "David Fincher",
    actors: [
      { id: 1, actor: "Brad Pitt" },
      { id: 2, actor: "Edward Norton" },
      { id: 3, actor: "Martha1" },
      { id: 4, actor: "Martha2" },
      { id: 5, actor: "Martha3" },
    ],
    poster: "/images/Movies/Posters/11_Fight Club.jpg",
  },
  {
    id: 5,
    title: "Fight Club 3",
    year: 1999,
    rating: 8.3,
    category: "mind fuck",
    related: "",
    related_id: "3",
    director: "David Fincher",
    actors: [
      { id: 1, actor: "Brad Pitt" },
      { id: 2, actor: "Edward Norton" },
      { id: 3, actor: "Martha1" },
      { id: 4, actor: "Martha2" },
      { id: 5, actor: "Martha3" },
    ],
    poster: "/images/Movies/Posters/11_Fight Club.jpg",
  },
  {
    id: 6,
    title: "Fight Club 3",
    year: 1999,
    rating: 8.3,
    category: "mind fuck",
    related: "",
    related_id: "3",
    director: "David Fincher",
    actors: [
      { id: 1, actor: "Brad Pitt" },
      { id: 2, actor: "Edward Norton" },
      { id: 3, actor: "Martha1" },
      { id: 4, actor: "Martha2" },
      { id: 5, actor: "Martha3" },
    ],
    poster: "/images/Movies/Posters/11_Fight Club.jpg",
  },
  {
    id: 7,
    title: "Fight Club 3",
    year: 1999,
    rating: 8.3,
    category: "mind fuck",
    related: "",
    related_id: "3",
    director: "David Fincher",
    actors: [
      { id: 1, actor: "Brad Pitt" },
      { id: 2, actor: "Edward Norton" },
      { id: 3, actor: "Martha1" },
      { id: 4, actor: "Martha2" },
      { id: 5, actor: "Martha3" },
    ],
    poster: "/images/Movies/Posters/11_Fight Club.jpg",
  },
  {
    id: 8,
    title: "Fight Club 3",
    year: 1999,
    rating: 8.3,
    category: "mind fuck",
    related: "",
    related_id: "3",
    director: "David Fincher",
    actors: [
      { id: 1, actor: "Brad Pitt" },
      { id: 2, actor: "Edward Norton" },
      { id: 3, actor: "Martha1" },
      { id: 4, actor: "Martha2" },
      { id: 5, actor: "Martha3" },
    ],
    poster: "/images/Movies/Posters/11_Fight Club.jpg",
  },
  {
    id: 9,
    title: "Fight Club 3",
    year: 1999,
    rating: 8.3,
    category: "mind fuck",
    related: "",
    related_id: "3",
    director: "David Fincher",
    actors: [
      { id: 1, actor: "Brad Pitt" },
      { id: 2, actor: "Edward Norton" },
      { id: 3, actor: "Martha1" },
      { id: 4, actor: "Martha2" },
      { id: 5, actor: "Martha3" },
    ],
    poster: "/images/Movies/Posters/11_Fight Club.jpg",
  },
  {
    id: 10,
    title: "Fight Club 3",
    year: 1999,
    rating: 8.3,
    category: "mind fuck",
    related: "",
    related_id: "3",
    director: "David Fincher",
    actors: [
      { id: 1, actor: "Brad Pitt" },
      { id: 2, actor: "Edward Norton" },
      { id: 3, actor: "Martha1" },
      { id: 4, actor: "Martha2" },
      { id: 5, actor: "Martha3" },
    ],
    poster: "/images/Movies/Posters/11_Fight Club.jpg",
  },
  {
    id: 11,
    title: "Fight Club 3",
    year: 1999,
    rating: 8.3,
    category: "mind fuck",
    related: "",
    related_id: "3",
    director: "David Fincher",
    actors: [
      { id: 1, actor: "Brad Pitt" },
      { id: 2, actor: "Edward Norton" },
      { id: 3, actor: "Martha1" },
      { id: 4, actor: "Martha2" },
      { id: 5, actor: "Martha3" },
    ],
    poster: "/images/Movies/Posters/11_Fight Club.jpg",
  },
  {
    id: 12,
    title: "Fight Club 3",
    year: 1999,
    rating: 8.3,
    category: "mind fuck",
    related: "",
    related_id: "3",
    director: "David Fincher",
    actors: [
      { id: 1, actor: "Brad Pitt" },
      { id: 2, actor: "Edward Norton" },
      { id: 3, actor: "Martha1" },
      { id: 4, actor: "Martha2" },
      { id: 5, actor: "Martha3" },
    ],
    poster: "/images/Movies/Posters/11_Fight Club.jpg",
  },
  {
    id: 13,
    title: "Fight Club 3",
    year: 1999,
    rating: 8.3,
    category: "mind fuck",
    related: "",
    related_id: "3",
    director: "David Fincher",
    actors: [
      { id: 1, actor: "Brad Pitt" },
      { id: 2, actor: "Edward Norton" },
      { id: 3, actor: "Martha1" },
      { id: 4, actor: "Martha2" },
      { id: 5, actor: "Martha3" },
    ],
    poster: "/images/Movies/Posters/11_Fight Club.jpg",
  },
  {
    id: 14,
    title: "Fight Club 3",
    year: 1999,
    rating: 8.3,
    category: "mind fuck",
    related: "",
    related_id: "3",
    director: "David Fincher",
    actors: [
      { id: 1, actor: "Brad Pitt" },
      { id: 2, actor: "Edward Norton" },
      { id: 3, actor: "Martha1" },
      { id: 4, actor: "Martha2" },
      { id: 5, actor: "Martha3" },
    ],
    poster: "/images/Movies/Posters/11_Fight Club.jpg",
  },
  {
    id: 15,
    title: "Fight Club 3",
    year: 1999,
    rating: 8.3,
    category: "mind fuck",
    related: "",
    related_id: "3",
    director: "David Fincher",
    actors: [
      { id: 1, actor: "Brad Pitt" },
      { id: 2, actor: "Edward Norton" },
      { id: 3, actor: "Martha1" },
      { id: 4, actor: "Martha2" },
      { id: 5, actor: "Martha3" },
    ],
    poster: "/images/Movies/Posters/11_Fight Club.jpg",
  },
  {
    id: 16,
    title: "Fight Club 3",
    year: 1999,
    rating: 8.3,
    category: "mind fuck",
    related: "",
    related_id: "3",
    director: "David Fincher",
    actors: [
      { id: 1, actor: "Brad Pitt" },
      { id: 2, actor: "Edward Norton" },
      { id: 3, actor: "Martha1" },
      { id: 4, actor: "Martha2" },
      { id: 5, actor: "Martha3" },
    ],
    poster: "/images/Movies/Posters/11_Fight Club.jpg",
  },
  {
    id: 17,
    title: "Fight Club 3",
    year: 1999,
    rating: 8.3,
    category: "mind fuck",
    related: "",
    related_id: "3",
    director: "David Fincher",
    actors: [
      { id: 1, actor: "Brad Pitt" },
      { id: 2, actor: "Edward Norton" },
      { id: 3, actor: "Martha1" },
      { id: 4, actor: "Martha2" },
      { id: 5, actor: "Martha3" },
    ],
    poster: "/images/Movies/Posters/11_Fight Club.jpg",
  },
  {
    id: 18,
    title: "Fight Club 3",
    year: 1999,
    rating: 8.3,
    category: "mind fuck",
    related: "",
    related_id: "3",
    director: "David Fincher",
    actors: [
      { id: 1, actor: "Brad Pitt" },
      { id: 2, actor: "Edward Norton" },
      { id: 3, actor: "Martha1" },
      { id: 4, actor: "Martha2" },
      { id: 5, actor: "Martha3" },
    ],
    poster: "/images/Movies/Posters/11_Fight Club.jpg",
  },
  {
    id: 19,
    title: "Fight Club 3",
    year: 1999,
    rating: 8.3,
    category: "mind fuck",
    related: "",
    related_id: "3",
    director: "David Fincher",
    actors: [
      { id: 1, actor: "Brad Pitt" },
      { id: 2, actor: "Edward Norton" },
      { id: 3, actor: "Martha1" },
      { id: 4, actor: "Martha2" },
      { id: 5, actor: "Martha3" },
    ],
    poster: "/images/Movies/Posters/11_Fight Club.jpg",
  },
  {
    id: 20,
    title: "Fight Club 3",
    year: 1999,
    rating: 8.3,
    category: "mind fuck",
    related: "",
    related_id: "3",
    director: "David Fincher",
    actors: [
      { id: 1, actor: "Brad Pitt" },
      { id: 2, actor: "Edward Norton" },
      { id: 3, actor: "Martha1" },
      { id: 4, actor: "Martha2" },
      { id: 5, actor: "Martha3" },
    ],
    poster: "/images/Movies/Posters/11_Fight Club.jpg",
  },
  {
    id: 21,
    title: "Fight Club 3",
    year: 1999,
    rating: 8.3,
    category: "mind fuck",
    related: "",
    related_id: "3",
    director: "David Fincher",
    actors: [
      { id: 1, actor: "Brad Pitt" },
      { id: 2, actor: "Edward Norton" },
      { id: 3, actor: "Martha1" },
      { id: 4, actor: "Martha2" },
      { id: 5, actor: "Martha3" },
    ],
    poster: "/images/Movies/Posters/11_Fight Club.jpg",
  },
  {
    id: 22,
    title: "Fight Club 3",
    year: 1999,
    rating: 8.3,
    category: "mind fuck",
    related: "",
    related_id: "3",
    director: "David Fincher",
    actors: [
      { id: 1, actor: "Brad Pitt" },
      { id: 2, actor: "Edward Norton" },
      { id: 3, actor: "Martha1" },
      { id: 4, actor: "Martha2" },
      { id: 5, actor: "Martha3" },
    ],
    poster: "/images/Movies/Posters/11_Fight Club.jpg",
  },
];
