export const movies = [
  {
    poster: "/images/Movies/Posters/01_The Shawshank Redemption.jpg",
    id: "1",
    title: "The Shawshank Redemption",
    rating: 9.3, // Actual IMDb rating
    year: 1994, // Corrected year
    category: "Drama", // Corrected category
    related: "fight_club",
    related_id: "1",
    director: "Frank Darabont", // Corrected director
    actors: [
      { id: 1, actor: "Tim Robbins" },
      { id: 2, actor: "Morgan Freeman" },
      { id: 3, actor: "Bob Gunton" },
      { id: 4, actor: "William Sadler" },
      { id: 5, actor: "Clancy Brown" },
    ],
  },
  {
    poster: "/images/Movies/Posters/02.01_The Godfather 1.jpg",
    id: "2.01",
    title: "The Godfather 1",
    rating: 9.2, // Actual IMDb rating
    year: 1972, // Corrected year
    category: "Crime-Drama", // Corrected category
    related: "fight_club",
    related_id: "1",
    director: "Francis Ford Coppola", // Corrected director
    actors: [
      { id: 1, actor: "Marlon Brando" },
      { id: 2, actor: "Al Pacino" },
      { id: 3, actor: "James Caan" },
      { id: 4, actor: "Richard S. Castellano" },
      { id: 5, actor: "Sterling Hayden" },
    ],
  },
  {
    poster: "/images/Movies/Posters/02.02_The Gadfather 2.jpg",
    id: "2.02",
    title: "The Godfather Part II",
    rating: 9.0, // Actual IMDb rating
    year: 1974, // Corrected year
    category: "Crime-Drama", // Corrected category
    related: "fight_club",
    related_id: "1",
    director: "Francis Ford Coppola", // Corrected director
    actors: [
      { id: 1, actor: "Al Pacino" },
      { id: 2, actor: "Robert De Niro" },
      { id: 3, actor: "Diane Keaton" },
      { id: 4, actor: "John Marley" },
      { id: 5, actor: "Richard S. Castellano" },
    ],
  },
  {
    poster: "/images/Movies/Posters/02.03_The Godfather 3.jpg",
    id: "2.03",
    title: "The Godfather Part III",
    rating: 7.6, // Actual IMDb rating
    year: 1990, // Corrected year
    category: "Crime-Drama", // Corrected category
    related: "fight_club",
    related_id: "1",
    director: "Francis Ford Coppola", // Corrected director
    actors: [
      { id: 1, actor: "Al Pacino" },
      { id: 2, actor: "Diane Keaton" },
      { id: 3, actor: "Andy Garcia" },
      { id: 4, actor: "Talia Shire" },
      { id: 5, actor: "Joe Mantegna" },
    ],
  },
  {
    poster: "/images/Movies/Posters/03.01_Batman Begins.jpg",
    id: "3.01",
    title: "Batman Begins",
    rating: 8.2, // Actual IMDb rating
    year: 2005, // Corrected year
    category: "Action-Adventure", // Corrected category
    related: "fight_club",
    related_id: "1",
    director: "Christopher Nolan", // Corrected director
    actors: [
      { id: 1, actor: "Christian Bale" },
      { id: 2, actor: "Michael Caine" },
      { id: 3, actor: "Liam Neeson" },
      { id: 4, actor: "Katie Holmes" },
      { id: 5, actor: "Gary Oldman" },
    ],
  },
  {
    poster: "/images/Movies/Posters/03.02_The Dark Knight.jpg",
    id: "3.02",
    title: "The Dark Knight",
    rating: 9.0, // Actual IMDb rating
    year: 2008, // Corrected year
    category: "Action-Crime", // Corrected category
    related: "fight_club",
    related_id: "1",
    director: "Christopher Nolan", // Corrected director
    actors: [
      { id: 1, actor: "Christian Bale" },
      { id: 2, actor: "Heath Ledger" },
      { id: 3, actor: "Aaron Eckhart" },
      { id: 4, actor: "Maggie Gyllenhaal" },
      { id: 5, actor: "Gary Oldman" },
    ],
  },
  {
    poster: "/images/Movies/Posters/03.03_The Dark Knight rises.jpg",
    id: "3.03",
    title: "The Dark Knight Rises",
    rating: 8.4, // Actual IMDb rating
    year: 2012, // Corrected year
    category: "Action-Adventure", // Corrected category
    related: "fight_club",
    related_id: "1",
    director: "Christopher Nolan", // Corrected director
    actors: [
      { id: 1, actor: "Christian Bale" },
      { id: 2, actor: "Tom Hardy" },
      { id: 3, actor: "Anne Hathaway" },
      { id: 4, actor: "Gary Oldman" },
      { id: 5, actor: "Joseph Gordon-Levitt" },
    ],
  },
  {
    poster: "/images/Movies/Posters/05_12 Angry Men.jpg",
    id: "5",
    title: "12 Angry Men",
    rating: 9.0, // Actual IMDb rating
    year: 1957, // Corrected year
    category: "Drama", // Corrected category
    related: "fight_club",
    related_id: "1",
    director: "Sidney Lumet", // Corrected director
    actors: [
      { id: 1, actor: "Henry Fonda" },
      { id: 2, actor: "Lee J. Cobb" },
      { id: 3, actor: "Martin Balsam" },
      { id: 4, actor: "John Fiedler" },
      { id: 5, actor: "E.G. Marshall" },
    ],
  },
  {
    poster: "/images/Movies/Posters/06_Schindler's List.jpg",
    id: "6",
    title: "Schindler's List",
    rating: 9.0, // Actual IMDb rating
    year: 1993, // Corrected year
    category: "Biography-Drama", // Corrected category
    related: "fight_club",
    related_id: "1",
    director: "Steven Spielberg", // Corrected director
    actors: [
      { id: 1, actor: "Liam Neeson" },
      { id: 2, actor: "Ben Kingsley" },
      { id: 3, actor: "Ralph Fiennes" },
      { id: 4, actor: "Caroline Goodall" },
      { id: 5, actor: "Jonathan Sagall" },
    ],
  },
  // {
  //   poster:
  //     "/images/Movies/Posters/07.01_The Hobbit - An Unexpected Journey.jpg",
  //   id: "7.01",
  //   title: "The Hobbit - An Unexpected Journey",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster:
  //     "/images/Movies/Posters/07.02_The Hobbit - The Desolation of Smaug.jpg",
  //   id: "7.02",
  //   title: "The Hobbit - The Desolation of Smaug",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster:
  //     "/images/Movies/Posters/07.03_The Hobbit - The Battle of the Five Armies.jpg",
  //   id: "7.03",
  //   title: "The Hobbit - The Battle of the Five Armies",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/07.04_The Lord of the Rings 1.jpg",
  //   id: "7.04",
  //   title: "The Lord of the Rings 1",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/07.05_The Lord of the Rings 2.jpg",
  //   id: "7.05",
  //   title: "The Lord of the Rings 2",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/07.06_The Lord of the Rings 3.jpg",
  //   id: "7.06",
  //   title: "The Lord of the Rings 3",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/08_Pulp Fiction.jpg",
  //   id: "8",
  //   title: "Pulp Fiction",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/09_The good, the bad and the ugly.jpg",
  //   id: "9",
  //   title: "The good, the bad and the ugly",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/10_Forrest Gump.jpg",
  //   id: "10",
  //   title: "Forrest Gump",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/11_Fight Club.jpg",
  //   id: "11",
  //   title: "Fight Club",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/12_Inception.jpg",
  //   id: "12",
  //   title: "Inception",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/15.01_Star Wars - The Phantom Menace.jpg",
  //   id: "15.01",
  //   title: "Star Wars - The Phantom Menace",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/15.02_Star Wars - Attack of the Clones.jpg",
  //   id: "15.02",
  //   title: "Star Wars - Attack of the Clones",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/15.03_Star Wars - Revenge of the Sith.jpg",
  //   id: "15.03",
  //   title: "Star Wars - Revenge of the Sith",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/15.04_Star Wars - Rogue One.jpg",
  //   id: "15.04",
  //   title: "Star Wars - Rogue One",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/15.05_Star Wars - Solo.jpg",
  //   id: "15.05",
  //   title: "Star Wars - Solo",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/15.06_Star Wars - A New Hope.jpg",
  //   id: "15.06",
  //   title: "Star Wars - A New Hope",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster:
  //     "/images/Movies/Posters/15.07_Star Wars - The Empire Strikes Back.jpg",
  //   id: "15.07",
  //   title: "Star Wars - The Empire Strikes Back",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/15.08_Star Wars - Return of the Jedi.jpg",
  //   id: "15.08",
  //   title: "Star Wars - Return of the Jedi",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/15.09_Star Wars - The Force Awakens.jpg",
  //   id: "15.09",
  //   title: "Star Wars - The Force Awakens",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/15.10_Star Wars - The Last Jedi.jpg",
  //   id: "15.1",
  //   title: "Star Wars - The Last Jedi",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster:
  //     "/images/Movies/Posters/15.11_Star Wars - The Rise of Skywalker.jpg",
  //   id: "15.11",
  //   title: "Star Wars - The Rise of Skywalker",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/16.01_The Matrix 1.jpg",
  //   id: "16.01",
  //   title: "The Matrix 1",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/16.02_The Matrix Reloaded.jpg",
  //   id: "16.02",
  //   title: "The Matrix Reloaded",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/16.03_The Matrix Revolutions.jpg",
  //   id: "16.03",
  //   title: "The Matrix Revolutions",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/16.04_The Matrix Resurrections.jpg",
  //   id: "16.04",
  //   title: "The Matrix Resurrections",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/17_Goodfellas.jpg",
  //   id: "17",
  //   title: "Goodfellas",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/18.01_Dune 1.jpg",
  //   id: "18.01",
  //   title: "Dune 1",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/18.02_Dune 2.jpg",
  //   id: "18.02",
  //   title: "Dune 2",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/19_One Flew over the Cuckoo's Nest.jpg",
  //   id: "19",
  //   title: "One Flew over the Cuckoo's Nest",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/20_Seven.jpg",
  //   id: "20",
  //   title: "Seven",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/21_Interstellar.jpg",
  //   id: "21",
  //   title: "Interstellar",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/23_The Silence of the Lambs.jpg",
  //   id: "23",
  //   title: "The Silence of the Lambs",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/24_Saving Private Ryan.jpg",
  //   id: "24",
  //   title: "Saving Private Ryan",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/25.01_City of God.jpg",
  //   id: "25.01",
  //   title: "City of God",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/25.02_Elite Squad 1.jpg",
  //   id: "25.02",
  //   title: "Elite Squad 1",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/25.03_Elite Squad 2.jpg",
  //   id: "25.03",
  //   title: "Elite Squad 2",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/27_Life is Beautiful.jpg",
  //   id: "27",
  //   title: "Life is Beautiful",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/28_The Green Mile.jpg",
  //   id: "28",
  //   title: "The Green Mile",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/29.01_The Terminator 1.jpg",
  //   id: "29.01",
  //   title: "The Terminator 1",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/29.02_Terminator 2 - Judgment Day.jpg",
  //   id: "29.02",
  //   title: "Terminator 2 - Judgment Day",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster:
  //     "/images/Movies/Posters/29.03_Terminator 3 - Rise of the Machines.jpg",
  //   id: "29.03",
  //   title: "Terminator 3 - Rise of the Machines",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/29.04_Terminator Salvation.jpg",
  //   id: "29.04",
  //   title: "Terminator Salvation",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/29.05_Terminator Genisys.jpg",
  //   id: "29.05",
  //   title: "Terminator Genisys",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/29.06_Terminator Dark Fate.jpg",
  //   id: "29.06",
  //   title: "Terminator Dark Fate",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/31.01_Back to the Future 1.jpg",
  //   id: "31.01",
  //   title: "Back to the Future 1",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/31.02_Back to the Future 2.jpg",
  //   id: "31.02",
  //   title: "Back to the Future 2",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/31.03_Back to the Future 3.jpg",
  //   id: "31.03",
  //   title: "Back to the Future 3",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/32_Spirit Away.jpg",
  //   id: "32",
  //   title: "Spirit Away",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/33_The Pianist.jpg",
  //   id: "33",
  //   title: "The Pianist",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/34_Parasite.jpg",
  //   id: "34",
  //   title: "Parasite",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/37_Gladiator.jpg",
  //   id: "37",
  //   title: "Gladiator",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/39_Leon.jpg",
  //   id: "39",
  //   title: "Leon",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/40_The Departed.jpg",
  //   id: "40",
  //   title: "The Departed",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/41_American History X.jpg",
  //   id: "41",
  //   title: "American History X",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/42_Whiplash.jpg",
  //   id: "42",
  //   title: "Whiplash",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/43_The Prestige.jpg",
  //   id: "43",
  //   title: "The Prestige",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/44_Grave of the Fireflies.jpg",
  //   id: "44",
  //   title: "Grave of the Fireflies",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/46_The Usual Suspects.jpg",
  //   id: "46",
  //   title: "The Usual Suspects",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/48_The Intouchables.jpg",
  //   id: "48",
  //   title: "The Intouchables",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/49_Cinema Paradiso.jpg",
  //   id: "49",
  //   title: "Cinema Paradiso",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/52_Once Upon a Time in the West.jpg",
  //   id: "52",
  //   title: "Once Upon a Time in the West",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/53.01_Prometheus.jpg",
  //   id: "53.01",
  //   title: "Prometheus",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/53.02_Alien Covenant.jpg",
  //   id: "53.02",
  //   title: "Alien Covenant",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/53.03_Alien.jpg",
  //   id: "53.03",
  //   title: "Alien",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/53.04_Aliens.jpg",
  //   id: "53.04",
  //   title: "Aliens",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/53.05_Alien 3.jpg",
  //   id: "53.05",
  //   title: "Alien 3",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/53.06_Alien Resurrection.jpg",
  //   id: "53.06",
  //   title: "Alien Resurrection",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/55_Django Unchained.jpg",
  //   id: "55",
  //   title: "Django Unchained",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/56_Apocalypse Now.jpg",
  //   id: "56",
  //   title: "Apocalypse Now",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/57_Memento.jpg",
  //   id: "57",
  //   title: "Memento",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster:
  //     "/images/Movies/Posters/60.01_Indiana Jones - Raiders of the Lost Ark.jpg",
  //   id: "60.01",
  //   title: "Indiana Jones - Raiders of the Lost Ark",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster:
  //     "/images/Movies/Posters/60.02_Indiana Jones and the Temple of Doom.jpg",
  //   id: "60.02",
  //   title: "Indiana Jones and the Temple of Doom",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster:
  //     "/images/Movies/Posters/60.03_Indiana Jones and the Last Crusade.jpg",
  //   id: "60.03",
  //   title: "Indiana Jones and the Last Crusade",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster:
  //     "/images/Movies/Posters/60.04_Indiana Jones and the Kingdom of the Crystal Skull.jpg",
  //   id: "60.04",
  //   title: "Indiana Jones and the Kingdom of the Crystal Skull",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster:
  //     "/images/Movies/Posters/60.05_Indiana Jones and the Dial of Destiny.jpg",
  //   id: "60.05",
  //   title: "Indiana Jones and the Dial of Destiny",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/61_The Lives of Others.jpg",
  //   id: "61",
  //   title: "The Lives of Others",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/64.01_The Avengers.jpg",
  //   id: "64.01",
  //   title: "The Avengers",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/64.02_The Avengers Age of Ultron.jpg",
  //   id: "64.02",
  //   title: "The Avengers Age of Ultron",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/64.03_Avengers Infinity War.jpg",
  //   id: "64.03",
  //   title: "Avengers Infinity War",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/64.04_Avengers Endgame.jpg",
  //   id: "64.04",
  //   title: "Avengers Endgame",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/67_The Shining.jpg",
  //   id: "67",
  //   title: "The Shining",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/70_Inglorious Basterds.jpg",
  //   id: "70",
  //   title: "Inglorious Basterds",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/73_American Beauty.jpg",
  //   id: "73",
  //   title: "American Beauty",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/74_Oldboy.jpg",
  //   id: "74",
  //   title: "Oldboy",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/76_Amadeus.jpg",
  //   id: "76",
  //   title: "Amadeus",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/78_Das Boot.jpg",
  //   id: "78",
  //   title: "Das Boot",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/80_Braveheart.jpg",
  //   id: "80",
  //   title: "Braveheart",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/81_Joker.jpg",
  //   id: "81",
  //   title: "Joker",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/82_Princess Mononoke.jpg",
  //   id: "82",
  //   title: "Princess Mononoke",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/83_Good Will Hunting.jpg",
  //   id: "83",
  //   title: "Good Will Hunting",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/84_Your Name.jpg",
  //   id: "84",
  //   title: "Your Name",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/85_Once Upon a Time in America.jpg",
  //   id: "85",
  //   title: "Once Upon a Time in America",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/89_Capernaum.jpg",
  //   id: "89",
  //   title: "Capernaum",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/90_Requiem for a Dream.jpg",
  //   id: "90",
  //   title: "Requiem for a Dream",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/91_Come and See.jpg",
  //   id: "91",
  //   title: "Come and See",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/94_Oppenheimer.jpg",
  //   id: "94",
  //   title: "Oppenheimer",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster:
  //     "/images/Movies/Posters/95_Eternal Sunshine of the Spotless Mind.jpg",
  //   id: "95",
  //   title: "Eternal Sunshine of the Spotless Mind",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/96_The Hunt.jpg",
  //   id: "96",
  //   title: "The Hunt",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/97_2001 a Space Odyssey.jpg",
  //   id: "97",
  //   title: "2001 a Space Odyssey",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/98_Reservoir Dogs.jpg",
  //   id: "98",
  //   title: "Reservoir Dogs",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/103_Incendies.jpg",
  //   id: "103",
  //   title: "Incendies",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/108_Scarface.jpg",
  //   id: "108",
  //   title: "Scarface",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/109_Full Metal Jacket.jpg",
  //   id: "109",
  //   title: "Full Metal Jacket",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/110_Amelie.jpg",
  //   id: "110",
  //   title: "Amelie",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/111_Heat.jpg",
  //   id: "111",
  //   title: "Heat",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/112_A Clockwork Orange.jpg",
  //   id: "112",
  //   title: "A Clockwork Orange",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/115_The Sting.jpg",
  //   id: "115",
  //   title: "The Sting",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/116_A Separation.jpg",
  //   id: "116",
  //   title: "A Separation",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/118.01_Die Hard.jpg",
  //   id: "118.01",
  //   title: "Die Hard",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/118.02_Die Hard 2.jpg",
  //   id: "118.02",
  //   title: "Die Hard 2",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/118.03_Die Hard with a Vengeance.jpg",
  //   id: "118.03",
  //   title: "Die Hard with a Vengeance",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/118.04_Live Free or Die Hard.jpg",
  //   id: "118.04",
  //   title: "Live Free or Die Hard",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/118.05_A Good day to Die Hard.jpg",
  //   id: "118.05",
  //   title: "A Good day to Die Hard",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/121_Snatch.jpg",
  //   id: "121",
  //   title: "Snatch",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/123_L.A. Confidential.jpg",
  //   id: "123",
  //   title: "L.A. Confidential",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/124_1917.jpg",
  //   id: "124",
  //   title: "1917",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/126_Taxi Driver.jpg",
  //   id: "126",
  //   title: "Taxi Driver",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/127_Downfall.jpg",
  //   id: "127",
  //   title: "Downfall",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/128_The Truman Show.jpg",
  //   id: "128",
  //   title: "The Truman Show",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/129_For a Few Dollars More.jpg",
  //   id: "129",
  //   title: "For a Few Dollars More",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/131_The Wolf of Wall Street.jpg",
  //   id: "131",
  //   title: "The Wolf of Wall Street",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/133_Green Book.jpg",
  //   id: "133",
  //   title: "Green Book",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/135_The Father.jpg",
  //   id: "135",
  //   title: "The Father",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/139.01_Top Gun.jpg",
  //   id: "139.01",
  //   title: "Top Gun",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/139.02_Top Gun Maverick.jpg",
  //   id: "139.02",
  //   title: "Top Gun Maverick",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/140_Shutter Island.jpg",
  //   id: "140",
  //   title: "Shutter Island",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/141_There Will be Blood.jpg",
  //   id: "141",
  //   title: "There Will be Blood",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/142_Casino.jpg",
  //   id: "142",
  //   title: "Casino",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/143.01_Jurassic Park.jpg",
  //   id: "143.01",
  //   title: "Jurassic Park",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/143.02_Jurassic Park_The Lost World.jpg",
  //   id: "143.02",
  //   title: "Jurassic Park",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/143.03_Jurassic Park 3.jpg",
  //   id: "143.03",
  //   title: "Jurassic Park 3",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/143.04_Jurassic World.jpg",
  //   id: "143.04",
  //   title: "Jurassic World",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/143.05_Jurassic World Fallen Kingdom.jpg",
  //   id: "143.05",
  //   title: "Jurassic World Fallen Kingdom",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/143.06_Jurassic World Dominion.jpg",
  //   id: "143.06",
  //   title: "Jurassic World Dominion",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/145_The Sixth Sense.jpg",
  //   id: "145",
  //   title: "The Sixth Sense",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/146_Pan's Labyrinth.jpg",
  //   id: "146",
  //   title: "Pan's Labyrinth",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/147_Unforgiven.jpg",
  //   id: "147",
  //   title: "Unforgiven",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/148_No Country for Old Men.jpg",
  //   id: "148",
  //   title: "No Country for Old Men",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/149_A Beautiful Mind.jpg",
  //   id: "149",
  //   title: "A Beautiful Mind",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/150_The Thing.jpg",
  //   id: "150",
  //   title: "The Thing",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster:
  //     "/images/Movies/Posters/180.01_Harry Potter - And the Sorcerers Stone.jpg",
  //   id: "180.01",
  //   title: "Harry Potter - And the Sorcerers Stone",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster:
  //     "/images/Movies/Posters/180.02_Harry Potter - And the Chamber of Secrets.jpg",
  //   id: "180.02",
  //   title: "Harry Potter - And the Chamber of Secrets",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster:
  //     "/images/Movies/Posters/180.03_Harry Potter - And the Prisoner of Azkaban.jpg",
  //   id: "180.03",
  //   title: "Harry Potter - And the Prisoner of Azkaban",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster:
  //     "/images/Movies/Posters/180.04_Harry Potter - And the Goblet of Fire.jpg",
  //   id: "180.04",
  //   title: "Harry Potter - And the Goblet of Fire",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster:
  //     "/images/Movies/Posters/180.05_Harry Potter - And the Order of the Phoenix.jpg",
  //   id: "180.05",
  //   title: "Harry Potter - And the Order of the Phoenix",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster:
  //     "/images/Movies/Posters/180.06_Harry Potter - And the Half Blood Prince.jpg",
  //   id: "180.06",
  //   title: "Harry Potter - And the Half Blood Prince",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster:
  //     "/images/Movies/Posters/180.07_Harry Potter - And the Deathly Hallows Part 1.jpg",
  //   id: "180.07",
  //   title: "Harry Potter - And the Deathly Hallows Part 1",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster:
  //     "/images/Movies/Posters/180.08_Harry Potter - And the Deathly Hallows Part 2.jpg",
  //   id: "180.08",
  //   title: "Harry Potter - And the Deathly Hallows Part 2",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/251.01_Iron Man.jpg",
  //   id: "251.01",
  //   title: "Iron Man",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/251.02_Iron Man 2.jpg",
  //   id: "251.02",
  //   title: "Iron Man 2",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/251.03_Iron Man 3.jpg",
  //   id: "251.03",
  //   title: "Iron Man 3",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster:
  //     "/images/Movies/Posters/252.01_Captain America The first avenger.jpg",
  //   id: "252.01",
  //   title: "Captain America The first avenger",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster:
  //     "/images/Movies/Posters/252.02_Captain America The Winter Soldier.jpg",
  //   id: "252.02",
  //   title: "Captain America The Winter Soldier",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/252.03_Captain America Civil War.jpg",
  //   id: "252.03",
  //   title: "Captain America Civil War",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/253.01_Thor.jpg",
  //   id: "253.01",
  //   title: "Thor",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/253.02_Thor The Drak World.jpg",
  //   id: "253.02",
  //   title: "Thor The Drak World",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/253.03_Thor Ragnarok.jpg",
  //   id: "253.03",
  //   title: "Thor Ragnarok",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/253.04_Thor Love and Thunder.jpg",
  //   id: "253.04",
  //   title: "Thor Love and Thunder",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/254.01_Spider Man Homecoming.jpg",
  //   id: "254.01",
  //   title: "Spider Man Homecoming",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/254.02_Spider Man Far from home.jpg",
  //   id: "254.02",
  //   title: "Spider Man Far from home",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/254.03_Spider Man No way home.jpg",
  //   id: "254.03",
  //   title: "Spider Man No way home",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/255.01_The Incredible Hulk.jpg",
  //   id: "255.01",
  //   title: "The Incredible Hulk",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/256.01_Guardians of the Galaxy.jpg",
  //   id: "256.01",
  //   title: "Guardians of the Galaxy",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/256.02_Guardians of the Galaxy Vol 2.jpg",
  //   id: "256.02",
  //   title: "Guardians of the Galaxy Vol 2",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/256.03_Guardians of the Galaxy Vol 3.jpg",
  //   id: "256.03",
  //   title: "Guardians of the Galaxy Vol 3",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/257.01_Dr Strange.jpg",
  //   id: "257.01",
  //   title: "Dr Strange",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster:
  //     "/images/Movies/Posters/257.02_Dr Strange in the Multiverse of Madness.jpg",
  //   id: "257.02",
  //   title: "Dr Strange in the Multiverse of Madness",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/258.01_Ant-man.jpg",
  //   id: "258",
  //   title: "Ant-man",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/258.02_Ant-man and the Wasp.jpg",
  //   id: "258.02",
  //   title: "Ant-man and the Wasp",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/258.03_Ant-man Quantumania.jpg",
  //   id: "258.03",
  //   title: "Ant-man Quantumania",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/259.01_Black Panther.jpg",
  //   id: "259.01",
  //   title: "Black Panther",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/259.02_Black Panther Wakanda Forever.jpg",
  //   id: "259.02",
  //   title: "Black Panther Wakanda Forever",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/260.01_Captain Marvel.jpg",
  //   id: "260.01",
  //   title: "Captain Marvel",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/260.02_The Marvels.jpg",
  //   id: "260.02",
  //   title: "The Marvels",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/261_Black Widow.jpg",
  //   id: "261",
  //   title: "Black Widow",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster:
  //     "/images/Movies/Posters/262.01_Shang-Chi and the Legend of the Ten Rings.jpg",
  //   id: "262.01",
  //   title: "Shang-Chi and the Legend of the Ten Rings",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
  // {
  //   poster: "/images/Movies/Posters/263.01_Eternals.jpg",
  //   id: "263.01",
  //   title: "Eternals",
  //   rating: 8.3,
  //   year: 1999,
  //   category: "Action-Crime",
  //   related: "fight_club",
  //   related_id: "1",
  //   director: "David Fincher",
  //   actors: [
  //     { id: 1, actor: "Brad Pitt" },
  //     { id: 2, actor: "Edward Norton" },
  //     { id: 3, actor: "Martha1" },
  //     { id: 4, actor: "Martha2" },
  //     { id: 5, actor: "Martha3" },
  //   ],
  // },
];
